biojava/biojava

biojava3-structure/src/main/java/org/biojava/bio/structure/io/FileParsingParameters.java
biojava3-structure/src/main/java/org/biojava/bio/structure/io/LocalPDBDirectory.java
biojava3-structure/src/main/java/org/biojava/bio/structure/io/StructureIOFile.java
biojava3-structure/src/test/java/org/biojava/bio/structure/align/util/AtomCacheTest.java

Two important modifications over #228 :
- FETCH_IF_OUTDATED added: will check timestamps and update if file in local file system is older
- FORCE_DOWNLOAD: is now officially a force-only mode, i.e. it will download everything even if locally present and up-to-date

Adding new FetchBehavior: FETCH_IF_OUTDATED

---

biojava3-structure/src/main/java/org/biojava/bio/structure/AtomPositionMap.java
biojava3-structure/src/main/java/org/biojava/bio/structure/ResidueRange.java
biojava3-structure/src/main/java/org/biojava/bio/structure/ResidueRangeAndLength.java
biojava3-structure/src/main/java/org/biojava/bio/structure/align/client/StructureName.java
biojava3-structure/src/test/java/org/biojava/bio/structure/ResidueRangeTest.java
biojava3-structure/src/test/java/org/biojava/bio/structure/TestAtomCache.java
biojava3-structure/src/test/java/org/biojava/bio/structure/align/ce/TestSmallAlignment.java

a7bd1c4 is an important fix that would be nice to have in a Biojava 4 hotfix after the release.

ResidueRange bug fixes

---

biojava-core/src/main/java/org/biojava/nbio/core/sequence/features/Qualifier.java
biojava-core/src/test/java/org/biojava/nbio/core/sequence/io/GenbankReaderTest.java
biojava-core/src/test/java/org/biojava/nbio/core/sequence/loader/GenbankProxySequenceReaderTest.java

Added test against "coded_by" qualifier in CDS feature for simple example.

Add test for CDS>>"coded_by" values

---

biojava-structure/src/main/java/org/biojava/nbio/structure/io/util/FileDownloadUtils.java

I try to fix TimeoutException in the unit tests. I identified place where the exception occures and added solution (customised timeout to 20 sec).

Try to fix TimeoutException

---

biojava-core/src/main/java/org/biojava/nbio/core/sequence/ProteinSequence.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/features/Qualifier.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/loader/GenbankProxySequenceReader.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/location/InsdcParser.java
biojava-core/src/test/java/org/biojava/nbio/core/sequence/io/GenbankReaderTest.java
biojava-core/src/test/java/org/biojava/nbio/core/sequence/loader/GenbankProxySequenceReaderTest.java
biojava-core/src/test/java/org/biojava/nbio/core/sequence/loader/SimpleGenbankProxySequenceReaderTest.java
biojava-core/src/test/java/org/biojava/nbio/core/sequence/location/InsdcParserTest.java
biojava-core/src/test/resources/log4j2.xml
biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/align/ce/OptimalCECPMainTest.java
biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/domain/EcodInstallationTest.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/StructureAlignmentFactory.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/ce/CECalculator.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/ce/CeMain.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/ce/OptimalCECPMain.java
biojava-structure/src/main/java/org/biojava/nbio/structure/ecod/EcodDomain.java
biojava-structure/src/main/java/org/biojava/nbio/structure/ecod/EcodFactory.java
biojava-structure/src/main/java/org/biojava/nbio/structure/ecod/EcodInstallation.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/util/FileDownloadUtils.java
biojava-structure/src/test/java/org/biojava/nbio/structure/TestDNAAlignment.java
pom.xml

This adds improments to the ecod package for file format and memory usage.
It also merges the patch branch, which includes some genbank improvements.

ECOD updates + merge patch

---

biojava-core/src/main/java/org/biojava/nbio/core/sequence/AccessionID.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenericGenbankHeaderParser.java
biojava-core/src/test/java/org/biojava/nbio/core/sequence/loader/GenbankProxySequenceReaderTest.java

add accession version and GenBank GID number into AccessionID class

add place for version and GenBank GI number in AccessionID class

---

biojava-structure-gui/src/main/java/org/biojava/nbio/structure/align/gui/MenuCreator.java
biojava-structure-gui/src/main/java/org/biojava/nbio/structure/align/gui/MyDistMaxListener.java
biojava-structure-gui/src/main/java/org/biojava/nbio/structure/align/gui/aligpanel/AligPanel.java
biojava-structure-gui/src/main/java/org/biojava/nbio/structure/align/gui/jmol/StructureAlignmentJmol.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/model/AFPChain.java

The GUI classes have been extended in the symmetry project and the colors are controlled there, so the coloring options have been removed from the biojava code.

Undo changes in the StructureAlignment colors

---

biojava-core/src/main/java/org/biojava/nbio/core/exceptions/Messages.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenbankReader.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenbankSequenceParser.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenericInsdcHeaderFormat.java
biojava-core/src/test/resources/two-dnaseqs.gb
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/AllChemCompProvider.java
pom.xml
readme.md

I propose we merge all changes from master into minor. Other than the version number commits, I believe all of the commits are suitable for the 4.1.x line, rather than 5.0.0. I think that any differences are simply from pushing to the wrong branch.

Combine master and minor branches

---

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/StructureToolsTest.java
biojava-structure/src/main/java/org/biojava/nbio/structure/StructureTools.java
biojava-structure/src/test/java/org/biojava/nbio/structure/TestAltLocs.java

Fix #309 - Representative Atoms are backbone only

---

biojava-structure-gui/src/main/java/demo/DemoCeSymm.java
biojava-structure-gui/src/main/java/org/biojava/nbio/structure/symmetry/gui/SymmetryCalc.java
biojava-structure-gui/src/main/java/org/biojava/nbio/structure/symmetry/gui/SymmetryDisplay.java
biojava-structure-gui/src/main/java/org/biojava/nbio/structure/symmetry/gui/SymmetryGui.java
biojava-structure-gui/src/main/java/org/biojava/nbio/structure/symmetry/gui/SymmetryListener.java
biojava-structure/src/main/java/demo/DemoCeSymm.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/CESymmCalculator.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/CESymmParameters.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/CeSymm.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/CeSymmIterative.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/CeSymmUserArgumentProcessor.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/OpenRefiner.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/OrderDetectionFailedException.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/OrderDetector.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/Refiner.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/RefinerFailedException.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/SequenceFunctionOrderDetector.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/SingleRefiner.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/SymmOptimizer.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/SymmetryAxes.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/utils/SymmetryTools.java

From the symmetry project to **biojava.structure.symmetry**.
Only the finished and stable functionalities for the internal symmetry detection have been ported, leaving some experimental and in development methods in the symmetry project.
What is included?
* Calculate **optimal self-alignment** of a structure (by disallowing identity diagonal).
* Calculate internal symmetric **subunits** of a structure.
* Calculate the **symmetry axes** that relate all the internal subunits.
* Calculate the highest **point group** symmetry combining internal and quaternary symmetries.
* **SymmetryGUI** to trigger symmetry analysis choosing the parameters and visualizing the results in Jmol.
What is left in symmetry project for development?
* MULTIPLE Refiner: needs a graph representation and graph …

Import Internal Symmetry Code to BioJava #246

---

biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/ChainClusterer.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/ClusterMerger.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/ClusterProteinChains.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/ProteinChainExtractor.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/ProteinSequenceClusterer.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/QuatSymmetryDetector.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/SequenceAlignmentCluster.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/Subunits.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/UniqueSequenceList.java
biojava-structure/src/test/java/org/biojava/nbio/structure/symmetry/core/TestChainClusterer.java
biojava-structure/src/test/java/org/biojava/nbio/structure/symmetry/core/TestQuatSymmetryDetection.java

Adds some documentation. I don't completely understand this package, so a double-check from @pwrose would be appreciated.

Adding some documentation to the symmetry.core package

---

biojava-structure/src/main/java/org/biojava/nbio/structure/align/BioJavaStructureAlignment.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/ce/CeMain.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/fatcat/FatCat.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/fatcat/FatCatFlexible.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/fatcat/FatCatRigid.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/fatcat/calc/FatCatAligner.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/model/AFPChain.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/seq/SmithWaterman3Daligner.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/util/AlignmentTools.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/xml/AFPChainFlipper.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/xml/AFPChainXMLParser.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/CeSymm.java
biojava-structure/src/test/java/org/biojava/nbio/structure/align/ce/CeCPMainTest.java
biojava-structure/src/test/java/org/biojava/nbio/structure/align/multiple/TestAFPChainConversion.java

Discussion and reasons are in the corresponding issue #286.

Fix #286 by passing the algorithm name in AFPChain constructor

---

biojava-structure/src/main/java/org/biojava/nbio/structure/Atom.java
biojava-structure/src/main/java/org/biojava/nbio/structure/AtomImpl.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/ChargeAdder.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/FileParsingParameters.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/PDBFileParser.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/SimpleMMcifConsumer.java

Added new file parsing param -> params.setCreateAtomCharges(true);
Updated Atom and AtomImpl to allow for Charge information
Created a new class ChargeAdder to add Charges
Updated PDBFileParser and MMcifConsumer to add charges if the param is set to true
#331

Update to allow for atoms to handle per atom charge information.

---

biojava-structure/src/main/java/org/biojava/nbio/structure/Group.java
biojava-structure/src/main/java/org/biojava/nbio/structure/HetatomImpl.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/GroupToSDF.java

Added function to Group interface
Added function to HetatomImpl implementation of that interface

Added functionality to write groups to MDL molblocks (as strings)

---

biojava-aa-prop/pom.xml
biojava-alignment/pom.xml
biojava-core/pom.xml
biojava-genome/pom.xml
biojava-modfinder/pom.xml
biojava-ontology/pom.xml
biojava-phylo/pom.xml
biojava-protein-disorder/pom.xml
biojava-sequencing/pom.xml
biojava-structure-gui/pom.xml
biojava-structure/pom.xml
biojava-survival/pom.xml
biojava-ws/pom.xml

This should solve the issue with demos not being compiled or run #387. They are excluded from the jar but not from compiling.

Making demos compile but not package into jar #387

---

pom.xml

In preparation for next release, this bumps up the java version to 1.7
See discussion in mailing list here: http://mailman.open-bio.org/pipermail/biojava-l/2016-January/011445.html

Bumping up java version as discussed in mailing list

---

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/ecod/EcodInstallationTest.java
biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/ecod/EcodParseTest.java
biojava-structure/src/main/java/org/biojava/nbio/structure/Structure.java
biojava-structure/src/main/java/org/biojava/nbio/structure/StructureImpl.java
biojava-structure/src/main/java/org/biojava/nbio/structure/URLIdentifier.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/client/StructureName.java
biojava-structure/src/main/java/org/biojava/nbio/structure/ecod/EcodDomain.java
biojava-structure/src/main/java/org/biojava/nbio/structure/ecod/EcodInstallation.java
biojava-structure/src/test/java/org/biojava/nbio/structure/align/client/TestStructureName.java

- Update ECOD parse to work with recent versions
- Make ECOD support StructureIdentifier framework

Fix #384: ECOD improvements

---

biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/ChemCompGroupFactory.java
biojava-structure/src/main/java/org/biojava/nbio/structure/rcsb/PdbIdLists.java

This utility class allows to easily access lists of PDB IDs, such as all viruses, NMR structures, etc.

Utility class for retrieving lists of PDB IDs.

---

biojava-structure/src/main/java/org/biojava/nbio/structure/io/BondMaker.java
biojava-structure/src/test/java/org/biojava/nbio/structure/TestAltLocs.java

The bonds between atoms in alternate locations were not being made - I have now updated the bond maker so it makes all alternate location bonds

Updated the bond maker to make alternate location bonds

---

biojava-structure/src/main/java/org/biojava/nbio/structure/io/FileParsingParameters.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/DownloadChemCompProvider.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/SimpleMMcifConsumer.java
biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestParseOnAsymId.java

Updates to allow for parsing mmCif files and producing chains based on internal chain ids.

Adds parsing parameter and function to generated chains based on internal ids

---

biojava-structure/src/main/java/org/biojava/nbio/structure/DBRef.java
biojava-structure/src/main/java/org/biojava/nbio/structure/StructureTools.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/PDBFileParser.java
biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestDBRefParsing.java

The PDBFileParser has been modified to ensure that all lines are right-padded to 80 characters prior to parsing to prevent certain parsers failing if the line is shorter than the position of some of the later optional fields, e.g. in DBRef

Modified PDBParser to fix bug #330

---

biojava-sequencing/src/main/java/org/biojava/nbio/sequencing/io/fastq/package-info.java

Fixes for jdk8 javadoc errors

---

biojava-structure/src/main/java/org/biojava/nbio/structure/SubstructureIdentifier.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/DownloadChemCompProvider.java
biojava-structure/src/test/java/org/biojava/nbio/structure/align/util/AtomCacheTest.java

Fix for #449 
Incidentally also merges in the bugfix branch.

Fix #449 SeqRes missing from substructures

---

biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/DownloadChemCompProvider.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmtf/MmtfStructureReader.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmtf/MmtfStructureWriter.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmtf/MmtfUtils.java

Updates the DownloadChemCompProvider
1) Be able to alter the server
2) Added a flag to alter the way the urls are constructed.
3) New default location for ligands files
Mmtf Reader and Writer updated to store the single letter code as ? if applciable

Update to DownloadChemCompProvider

---

biojava-structure/src/main/java/org/biojava/nbio/structure/io/ChargeAdder.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/PDBFileParser.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/SimpleMMcifConsumer.java
biojava-structure/src/test/java/org/biojava/nbio/structure/TestChargeAdder.java

Where Biojava wasn't adding charges to all groups.
Changed the method to a static. 
Updated the PDBFileParser and the SimpleMMCifConsumer.
Added a basic test to check that charges are being added appropriately.

Refactored ChargeAdder and fixed bug

---

biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/SimpleMMcifParser.java

Updated MMCif Parser to handle non-numeric data in the NCS operator field

NCS operator field non-numeric value handling.

---

biojava-structure/src/main/java/org/biojava/nbio/structure/secstruc/SecStrucCalc.java
biojava-structure/src/test/java/org/biojava/nbio/structure/secstruc/TestSecStrucCalc.java

- Updated the test and the code to handle multi-model systems appropriately.
- Added a new test to show that multi-model systems are handled correctly.

Secondary structure information is now calculated for all models.

---

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/io/TestNcsOpsParsing.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/MMCIFFileTools.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/SimpleMMcifConsumer.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/SimpleMMcifParser.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/model/Cell.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/model/ChemComp.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/model/PdbxStructOperList.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/model/Refine.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/model/StructNcsOper.java

Following pull request #482 , this adapts mmcif reading to the new `CIFLabel` and `IgnoreField` tags

Adapted cif parser to use new CIFLabel and Ignorefield tags

---

biojava-core/src/main/java/org/biojava/nbio/core/alignment/SimpleAlignedSequence.java
biojava-core/src/main/java/org/biojava/nbio/core/alignment/SimpleSequencePair.java
biojava-core/src/main/java/org/biojava/nbio/core/alignment/template/AlignedSequence.java
biojava-core/src/main/java/org/biojava/nbio/core/alignment/template/SequencePair.java
biojava-core/src/test/java/org/biojava/nbio/core/alignment/SimpleAlignedSequenceTest.java
biojava-core/src/test/java/org/biojava/nbio/core/alignment/SimpleSequencePairTest.java

Small change that fixes issue #491.

Implement Util Methods for Sequence Identity and Coverage of Alignments

---

biojava-core/src/main/java/org/biojava/nbio/core/alignment/matrices/ScaledSubstitutionMatrix.java
biojava-core/src/main/java/org/biojava/nbio/core/util/SingleLinkageClusterer.java
biojava-ontology/src/main/java/org/biojava/nbio/ontology/obo/OboFileParser.java
biojava-ontology/src/main/java/org/biojava/nbio/ontology/utils/AbstractAnnotation.java
biojava-structure-gui/src/main/java/org/biojava/nbio/structure/symmetry/jmolScript/JmolSymmetryScriptGeneratorH.java
biojava-structure-gui/src/main/java/org/biojava/nbio/structure/symmetry/jmolScript/JmolSymmetryScriptGeneratorPointGroup.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/ce/AbstractUserArgumentProcessor.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/client/StructureName.java
biojava-structure/src/main/java/org/biojava/nbio/structure/contact/StructureInterface.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/GroupToSDF.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/MMCIFFileTools.java
biojava-structure/src/main/java/org/biojava/nbio/structure/secstruc/SecStrucState.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/HelixLayers.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/RotationGroup.java
biojava-structure/src/main/java/org/biojava/nbio/structure/xtal/CrystalBuilder.java

This pull request is focused on resolving occurrences of Sonar rule pmd:InefficientStringBuffering - Inefficient String Buffering
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=pmd:InefficientStringBuffering
M-Ezzat

pmd:InefficientStringBuffering - Inefficient String Buffering

---

biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmtf/MmtfStructureWriter.java
biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestHardBioUnits.java
biojava-structure/src/test/java/org/biojava/nbio/structure/io/mmtf/TestMmtfUtils.java
pom.xml

- Move to v0.2.2 
- Make one test more robust (I believe the number of the model is arbitrary - but let me know if I'm wrong)
- Make naming of Bioassemblies using key not a counter

Update to v0.2.2 of mmtf

---

biojava-structure-gui/src/main/java/org/biojava/nbio/structure/align/gui/DisplayAFP.java
biojava-structure-gui/src/main/java/org/biojava/nbio/structure/align/gui/MultipleAlignmentJmolDisplay.java
biojava-structure-gui/src/main/java/org/biojava/nbio/structure/align/gui/StructureAlignmentDisplay.java
biojava-structure-gui/src/main/java/org/biojava/nbio/structure/align/gui/jmol/MultipleAlignmentJmol.java
biojava-structure-gui/src/main/java/org/biojava/nbio/structure/align/gui/jmol/StructureAlignmentJmol.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/multiple/util/MultipleAlignmentTools.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/util/AlignmentTools.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/CESymmParameters.java

Move them from biojava-structure-gui to biojava-structure,
since generating the multi-model PDB files might be generally
useful.
This is required for the biojava-http project

Refactor methods for generating alignment PDBs

---

biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmtf/MmtfUtils.java
biojava-structure/src/test/java/org/biojava/nbio/structure/symmetry/core/TestQuatSymmetryDetector.java

Remove the useMmcif from test
Fix the bug and clean up the logic of adding seq res groups
https://github.com/biojava/biojava/issues/517

Fix issue 517 - debug mmtf reader

---

biojava-structure/src/main/java/org/biojava/nbio/structure/cath/CathFactory.java
biojava-structure/src/main/java/org/biojava/nbio/structure/cath/CathInstallation.java

This should fix the test problems for the moment. I didn't get a reply from cath yet, so don't know if the old URL is gone for good. In any case the new server layout seems to be well thought and solid, it looks like it is there to stay. One problem is I couldn't find the new file names for CathDomainDescriptionFile and CathNames, so that's a TODO for later.

Fix for issue 544

---

biojava-genome/pom.xml
biojava-genome/src/main/java/org/biojava/nbio/genome/parsers/genename/ChromPos.java
biojava-genome/src/main/java/org/biojava/nbio/genome/util/ChromosomeMappingTools.java
biojava-genome/src/test/java/org/biojava/nbio/genome/TestGenomeMapping.java

adding the new chromosome mapping tools to bugfix branch

Bugfixes 4.2

---

biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/SimpleMMcifConsumer.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmtf/MmtfStructureReader.java

Minor bugfix - for reading Deuterated 'nanoheterogenity' cases using MMTF

Fix a bug reading in Deuterated files using MMTF

---

biojava-structure/src/main/java/org/biojava/nbio/structure/HetatomImpl.java
biojava-structure/src/main/java/org/biojava/nbio/structure/ecod/EcodInstallation.java

The logic to check group type is the same as before, but the actual tests works differently. 
Also needed to fix the ECOD file parser, since there are some changes in the latest version that break junit tests.

Update test for type of group based on comments from @josemduarte

---

biojava-structure/src/main/java/org/biojava/nbio/structure/io/BondMaker.java
biojava-structure/src/test/java/org/biojava/nbio/structure/TestBond.java

- StructConn bonds now added
- Added test for this using 1CDR
https://github.com/rcsb/mmtf/issues/15

Struct conn record bonds now made for all models

---

biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenericInsdcHeaderFormat.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/utils/SymmetryTools.java
biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestMMcifOrganismParsing.java
biojava-survival/src/main/java/org/biojava/nbio/survival/cox/CoxInfo.java

* %r is not a valid formatting code and will result UnknownFormatConversionException. %s is the correct code to format the String as returned by your getStrand() method.
* Do not compare NaNs with ==. NaN is not equal to any number,   self including.
* Do not compare enum with String,  will never be equals.

GenericInsdcHeaderFormat: Fixed formatting codes.

---

biojava-genome/src/main/java/org/biojava/nbio/genome/parsers/gff/Location.java
biojava-genome/src/test/java/org/biojava/nbio/genome/TestIssue355.java
biojava-genome/src/test/java/org/biojava/nbio/genome/TestLocation.java

Interval intersection is wrongly computed. Here is the proposed alternative implementation. It passes the new TestIssue355 Unit test that exists in another branch.

Proposed fix for #355

---

biojava-structure-gui/src/main/java/org/biojava/nbio/structure/align/gui/jmol/JmolPanel.java

MMTF write support is much better than mmCIF. I'm assuming it will be faster as well.

Switch Jmol interaction to use MMTF

---

biojava-structure/src/main/java/org/biojava/nbio/structure/align/util/AtomCache.java
biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/SubunitExtractor.java
biojava-structure/src/test/java/org/biojava/nbio/structure/TestBioAssemblyIdentifier.java
biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestHardBioUnits.java

This switches the biounit generation by default to multichain biounits as discussed in #572

Solving #572

---

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/geometry/TestProteinSuperposition.java
biojava-structure/src/main/java/org/biojava/nbio/structure/Calc.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/util/AlignmentTools.java
biojava-structure/src/main/java/org/biojava/nbio/structure/geometry/CalcPoint.java
biojava-structure/src/main/java/org/biojava/nbio/structure/geometry/SuperPositionQCP.java
biojava-structure/src/main/java/org/biojava/nbio/structure/geometry/SuperPositionQuat.java
biojava-structure/src/main/java/org/biojava/nbio/structure/geometry/SuperPositionSVD.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/C2RotationSolver.java
biojava-structure/src/test/java/org/biojava/nbio/structure/geometry/TestSuperPosition.java

This also contains the integration test added by @josemduarte (I merged his branch).

Fix #588 and redo PR #576

---

biojava-genome/src/main/java/org/biojava/nbio/genome/util/ChromosomeMappingTools.java
biojava-modfinder/src/main/java/org/biojava/nbio/phosphosite/Dataset.java
biojava-modfinder/src/main/java/org/biojava/nbio/phosphosite/Site.java
biojava-modfinder/src/test/java/org/biojava/nbio/protmod/phosphosite/TestAcetylation.java

Also contains a few javadoc improvements.

fix for broken Phosphosite parser

---

biojava-structure-gui/src/main/java/org/biojava/nbio/structure/align/gui/jmol/StructureAlignmentJmol.java

For a course at university (ESOF) we were supposed to try to implement a new feature to this project.
Clicking with the right mouse button on the Structure-Gui panel, a menu is shown with properties and options: zooming, spinning, capturing as an image, recording a GIF, etc. However, we think that the using of the right click is not intuitive at all since there are options that, as previously said, can be set through controls that are already visible when the user interface is opened. This can induce users to think that there are no more available options. To avoid this problem we think that it would be easier if some of the most important options were available in the main window of the GUI.
Considering that zooming is one of the most important features to be able to visualize a protein …

Add Zoom and Spin Buttons in the Structure-Gui

---

biojava-modfinder/src/test/java/org/biojava/nbio/protmod/phosphosite/TestAcetylation.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/ChemicalComponentDictionary.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/chem/PolymerType.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/chem/ResidueType.java

Some cleanup to ResidueType and PolymerType enums. However the performance improvements are minimal so far.

#622 removal of a few loops.

---

biojava-genome/src/test/java/org/biojava/nbio/genome/TestGenomeMapping.java

unit test to check handling multiple UTRs preceding the coding region

Chromosome mapping tool: unit test 

---

biojava-ws/src/main/java/org/biojava/nbio/ws/hmmer/RemoteHmmerScan.java

The header was using "Accept:" when it should be "Accept".

Bugfix in hmmer web service

---

biojava-genome/src/main/java/org/biojava/nbio/genome/util/ChromosomeMappingTools.java

ChromosomeMappingTools patch

---

biojava-core/src/main/java/org/biojava/nbio/core/util/SequenceTools.java
biojava-genome/src/main/java/org/biojava/nbio/genome/util/ProteinMappingTools.java

- Protein mapping: proxy to translate DNA sequence so it can work with both, String and DNASequence
- An utility method to check if an array of sequences has sequences of equal length

Changes needed to fix dataframe generation pipeline 

---

.travis.yml
biojava-genome/src/main/java/org/biojava/nbio/genome/parsers/twobit/SimpleTwoBitFileProvider.java
biojava-genome/src/main/java/org/biojava/nbio/genome/util/ChromosomeMappingTools.java
biojava-genome/src/main/resources/log4j2.xml
biojava-genome/src/test/java/org/biojava/nbio/genome/TestGenomeMapping.java
biojava-protein-disorder/src/main/java/org/biojava/nbio/data/sequence/SequenceUtil.java
biojava-protein-disorder/src/test/java/org/biojava/nbio/ronn/JronnTest.java
travis-settings.xml

Bug fix to get CDS ranges without changing the original data

Get CDS ranges patch

---

biojava-core/src/main/java/org/biojava/nbio/core/alignment/SimpleAlignedSequence.java
biojava-core/src/main/java/org/biojava/nbio/core/alignment/template/AlignedSequence.java

Exposing alignment mappings to be able to map query sequence to target sequence

Sequence alignment mappings

---

biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/FastaReaderHelper.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/FileProxyRNASequenceCreator.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenbankReaderHelper.java

Added methods for reading RNA sequences by copy paste search replace.

Add methods for reading RNA sequences.

---

biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenbankReader.java
biojava-core/src/test/java/org/biojava/nbio/core/sequence/io/GenbankReaderTest.java

Fix for #663 with its test + updates on existing tests and some code cleaning.

Fix for #663

---

biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenericGenbankHeaderParser.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/template/AbstractSequence.java
biojava-core/src/test/java/org/biojava/nbio/core/sequence/io/GenbankReaderTest.java

Sorry for the previous wrong pull request. I hope this one is fine.

Set comments on AbstractSequence Object.

---

biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenbankSequenceParser.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenericGenbankHeaderParser.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/reference/AbstractReference.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/reference/GenbankReference.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/reference/ReferenceInterface.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/template/AbstractSequence.java
biojava-core/src/test/java/org/biojava/nbio/core/sequence/io/GenbankReaderTest.java

1. Added a new folder into main/java/org/biojava/nbio/core/sequence package
for Reference tag. It contains ReferenceInterface, AbstractReference and
GenbankReference (Only for Genbank format files).
2. Added List of AbstractReference with getter and setter into AbstractSequence.java.
3. Updated GenbankSequenceParser to parse the Reference tag.
4. Implemented addReference method in GenericGenbankHeaderParser because
some Genbank format file may contain multiple Reference tag.
5. Updated GenbankReaderTest with to check the Reference tag parsing process.

Add Reference tag parsing process for Genbank file.

---

biojava-ontology/src/main/java/org/biojava/nbio/ontology/obo/OboFileHandler.java
biojava-ontology/src/test/java/org/biojava/nbio/ontology/TestParseOBO.java

Biojava #695: Stores namespace as annotation

---

biojava-genome/src/main/java/org/biojava/nbio/genome/util/ChromosomeMappingTools.java
biojava-genome/src/test/java/org/biojava/nbio/genome/TestChromosomeMappingTools.java

Fixing bug in Chromosome Mapping Tools 

---

biojava-core/src/main/java/org/biojava/nbio/core/util/FlatFileCache.java
biojava-core/src/main/java/org/biojava/nbio/core/util/InputStreamProvider.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/client/FarmJobRunnable.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/DownloadChemCompProvider.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/SimpleMMcifParser.java
biojava-structure/src/test/java/org/biojava/nbio/structure/TestDownloadChemCompProvider.java

This solves #704 and adds some tests for #703

Some fixes related to caching and mmcif parsing

---

biojava-structure/src/main/java/org/biojava/nbio/structure/io/PDBFileParser.java
biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestShortLines.java

These are line-length bug fixes which are in the Master BioJava branch but not in the bugfixes-4.2 (4.2.8 branch).

CONECT/LINK line-length bug fix for the PDB Parser (already in BioJava Master branch).

---

biojava-structure/src/main/java/org/biojava/nbio/structure/Calc.java
biojava-structure/src/test/java/org/biojava/nbio/structure/TestCalc.java

Fixing issue with Calc.transform(Chain,Matrix4d)

---

biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/CeSymmResult.java

Fixes NPE reported at https://github.com/rcsb/symmetry/issues/92

Fix rcsb/symmetry#92: NullPointerException

---

biojava-ws/src/main/java/demo/HmmerDemo.java
biojava-ws/src/main/java/org/biojava/nbio/ws/hmmer/RemoteHmmerScan.java
biojava-ws/src/test/java/org/biojava/nbio/ws/hmmer/TestRemoteHmmerScan.java

Hmmer web service at EBI has moved to https

Fixing hmmer scan web service and adding test for it

---

biojava-core/src/main/java/org/biojava/nbio/core/alignment/SimpleSequencePair.java
biojava-core/src/main/java/org/biojava/nbio/core/alignment/template/SequencePair.java
biojava-core/src/test/java/org/biojava/nbio/core/alignment/SimpleSequencePairTest.java
biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/cluster/TestSubunitClustererExamples.java
biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/symmetry/TestQuatSymmetryDetectorExamples.java
biojava-integrationtest/src/test/resources/ce_1fdo.A_2iv2.X.out
biojava-structure-gui/src/main/java/demo/DemoQuatSymmetryJmol.java
biojava-structure/src/main/java/demo/DemoSymmetry.java
biojava-structure/src/main/java/org/biojava/nbio/structure/Calc.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/ce/CECalculator.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/ce/CeParameters.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/fatcat/calc/FatCatAligner.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/fatcat/calc/FatCatParameters.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/quaternary/QsAlign.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/quaternary/QsAlignParameters.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/util/AFPChainScorer.java
biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/Subunit.java
biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/SubunitCluster.java
biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/SubunitClusterUtils.java
biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/SubunitClusterer.java
biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/SubunitClustererMethod.java
biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/SubunitClustererParameters.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/QuatSymmetryDetector.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/utils/PowerSet.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/utils/SymmetryTools.java
biojava-structure/src/test/java/org/biojava/nbio/structure/cluster/TestSubunitCluster.java

More options for the clustering parameters and superposition algorithms.
I tried to preserve the previous default behaviour whenever possible.
@lafita Aleix, I believe most of the code I touched was written by you, could you please take a look? Thank you!

Small refactoring for more flexible symmetry detection.

---

biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/SimpleMMcifConsumer.java

Handle cases where the insertion code fields are missing (null).

Check for insertion code fields for null values.

---

biojava-structure/src/main/java/org/biojava/nbio/structure/StructureIO.java

Fixing docs

---

biojava-structure/src/main/java/org/biojava/nbio/structure/align/StructurePairAligner.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/helper/AlignUtils.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/multiple/MultipleAlignmentEnsembleImpl.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/pairwise/FragmentJoiner.java
biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/utils/SymmetryTools.java

Refactoring and docs as per #592

---

biojava-structure/src/main/java/org/biojava/nbio/structure/geometry/SuperPositionQCP.java
biojava-structure/src/test/java/org/biojava/nbio/structure/geometry/TestSuperPosition.java
biojava-structure/src/test/java/org/biojava/nbio/structure/geometry/TestSuperPositionQCP.java

Now the superposition can be calculated after the RMSD in a class
specific method.
I also added a test. This fixes #725

Reset the QCP 2-step calculation

---

HEADER.txt
LICENSE
development/addlicense.sh

With this the license displays nicely in the top bar and a summary shown when opening the LICENSE file

Standard LGPL license as provided by github template

---

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/ecod/EcodInstallationTest.java
biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/io/TestAtomCachePerformance.java
biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/io/TestLongPdbVsMmCifParsing.java
biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/symmetry/TestQuatSymmetryDetectorExamples.java
biojava-structure/src/main/java/org/biojava/nbio/structure/align/util/AtomCache.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/BondMaker.java
biojava-structure/src/test/java/org/biojava/nbio/structure/TestBond.java
biojava-structure/src/test/java/org/biojava/nbio/structure/TestDownloadChemCompProvider.java
biojava-structure/src/test/java/org/biojava/nbio/structure/asa/TestAsaCalc.java
biojava-structure/src/test/resources/log4j2.xml
pom.xml

Upgrading maven plugin versions. Fixed a few tests that were broken when running on maven.

Maven plugin upgrade

---

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/scop/BerkeleyScopInstallationTest.java
biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/scop/ScopDatabaseTest.java
biojava-structure/src/main/java/org/biojava/nbio/structure/cath/CathFactory.java
biojava-structure/src/main/java/org/biojava/nbio/structure/scop/ScopFactory.java

Add latest database versions for SCOP, CATH, and ECOD.

Update database versions

---

CHANGELOG.md

Please fill any gaps that you find by pull requesting to this branch or separate pull requests.
Note I did not manage to use clirr or revapi tools, so this is all based on manual reading of pull requests and issues.
I'll perform the release today in any case. The changelog can be finalised even after the release.

A changelog draft for the 5.0.0 release

---

biojava-ontology/src/main/java/org/biojava/nbio/ontology/obo/OboFileHandler.java
biojava-ontology/src/test/java/org/biojava/nbio/ontology/TestOboFileParsing.java

#731 
- Modified `OBOFileHandler.java` for triple `replaced_by`
- Added new file `hp.obo` (HPO OBO file) and added new test in `TestOBOFileParsing.java` to test new functionality for HPO OBO file

#731 OBO Parser: replaced_by

---

biojava-structure-gui/pom.xml
biojava-structure-gui/src/main/java/org/biojava/nbio/structure/align/gui/jmol/JmolPanel.java

This is a temporal solution while issue #629 is not fixed.

Update Jmol version and revert to MMCIF format for JmolPanel

---

CHANGELOG.md

Source of info was https://biojava.org/wiki/Current_events/

Extending back the changelog 

---

biojava-structure/src/main/java/org/biojava/nbio/structure/ChainImpl.java

fix for cloning with null seqres groups

---

biojava-structure/src/main/java/org/biojava/nbio/structure/EntityInfo.java
biojava-structure/src/test/java/org/biojava/nbio/structure/TestEntityResIndexMapping.java

Fixing issue 797

---

biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/DownloadChemCompProvider.java

After merging we can close #315

Fix a minor issue with logging described in #315

---

biojava-structure/src/main/java/org/biojava/nbio/structure/asa/AsaCalculator.java

Minor performance improvement by replacing lists with raw arrays. Some cleanup.

 Minor performance improvement in ASA calculation

---

pom.xml

Update maven-surefire-plugin version to 3.0.0-M1.

---

biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/ABITrace.java

added implementation of method parameter

---

biojava-structure/src/main/java/org/biojava/nbio/structure/asa/AsaCalculator.java
biojava-structure/src/main/java/org/biojava/nbio/structure/contact/StructureInterface.java
biojava-structure/src/main/java/org/biojava/nbio/structure/contact/StructureInterfaceList.java
biojava-structure/src/test/java/org/biojava/nbio/structure/asa/TestAsaCalc.java

Now neighbors are calculated with spatial hashing, improving performance dramatically for cases with many thousands of atoms. Also improved docs, logs and added new tests.

Improved ASA calculation performance

---

biojava-structure/src/main/java/org/biojava/nbio/structure/Atom.java
biojava-structure/src/main/java/org/biojava/nbio/structure/AtomImpl.java
biojava-structure/src/main/java/org/biojava/nbio/structure/Group.java
biojava-structure/src/main/java/org/biojava/nbio/structure/HetatomImpl.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/BondMaker.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/SimpleMMcifConsumer.java
biojava-structure/src/test/java/org/biojava/nbio/structure/TestAltLocs.java

As reported in https://github.com/rcsb/mmtf/issues/44

Fixing issue in bonds between atoms with different alt locs

---

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/contact/TestInterfaceFinder.java
biojava-structure/src/main/java/org/biojava/nbio/structure/StructureTools.java
biojava-structure/src/main/java/org/biojava/nbio/structure/contact/InterfaceFinder.java
biojava-structure/src/main/java/org/biojava/nbio/structure/contact/StructureInterface.java
biojava-structure/src/test/java/org/biojava/nbio/structure/contact/TestInterfaceFinder.java

New feature to find interfaces in a given`Structure` object. 
Some doc corrections are included.

New interface finder functionality

---

biojava-aa-prop/src/main/java/org/biojava/nbio/aaproperties/CommandPrompt.java
biojava-aa-prop/src/main/java/org/biojava/nbio/aaproperties/PeptideProperties.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/template/AbstractNucleotideCompoundSet.java
biojava-protein-disorder/src/main/java/org/biojava/nbio/ronn/Jronn.java

Hello-
I have written three for loops in java 8 streams, if you like it, kindly merge. Thanks

refactored code to use java 8 streams

---

biojava-core/src/main/java/org/biojava/nbio/core/sequence/features/DatabaseReferenceInterface.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/features/FeatureRetriever.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/features/FeaturesKeyWordInterface.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenbankReader.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenbankSequenceParser.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/loader/GenbankProxySequenceReader.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/loader/UniprotProxySequenceReader.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/location/InsdcLocations.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/location/InsdcParser.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/location/template/AbstractLocation.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/template/AbstractSequence.java
biojava-core/src/test/java/org/biojava/nbio/core/sequence/io/GenbankReaderTest.java
biojava-core/src/test/java/org/biojava/nbio/core/sequence/loader/GenbankProxySequenceReaderTest.java
biojava-genome/src/main/java/org/biojava/nbio/genome/homology/GFF3FromUniprotBlastHits.java
pom.xml

As per our conversation.
Cheers,
Paolo

#855 code cleaning not related to issue

---

.github/workflows/ci.yaml

On each push mvn verify will be executed on Ubuntu 18.04 and the latest Mac OS X using JDK 11

Added github actions to verify the build on each push

---

CHANGELOG.md
biojava-structure/src/main/java/demo/DemoLoadSecStruc.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmtf/MmtfUtils.java
biojava-structure/src/main/java/org/biojava/nbio/structure/secstruc/DSSPParser.java
biojava-structure/src/test/java/org/biojava/nbio/structure/TestDownloadChemCompProvider.java
biojava-structure/src/test/java/org/biojava/nbio/structure/secstruc/TestDSSPParser.java

Another breaking change for 6.0.0
Should fix #896

Removing support for fetching dssp files from RCSB (service deprecated)

---

biojava-structure/src/main/java/org/biojava/nbio/structure/asa/AsaCalculator.java
biojava-structure/src/test/java/org/biojava/nbio/structure/asa/TestAsaCalc.java

Implemented some of the ideas exposed in Eisenhaber et al 1994 (https://onlinelibrary.wiley.com/doi/epdf/10.1002/jcc.540160303). This results in ~x5 runtime improvement

Performance improvement in ASA calculation

---

biojava-structure/src/main/java/org/biojava/nbio/structure/align/pairwise/AltAligComparator.java

Fix issue 864

---

biojava-core/src/test/java/org/biojava/nbio/core/sequence/io/ABITracerTest.java

Added test for ABITrace#getTrace() method, which  lacked test coverage.
Thanks, great project.

ABITrace test coverage

---

biojava-core/src/main/java/org/biojava/nbio/core/util/FileDownloadUtils.java
biojava-core/src/test/java/org/biojava/nbio/core/alignment/matrices/SubstitutionMatrixTest.java
biojava-core/src/test/java/org/biojava/nbio/core/util/FileDownloadUtilsTest.java
biojava-core/src/test/java/org/biojava/nbio/core/util/PrettyXMLWriterTest.java

Fix recent unit tests fail on windows #970

---

biojava-structure/src/main/java/org/biojava/nbio/structure/io/PDBFileParser.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/cif/CifStructureConsumerImpl.java

In case there is only one revision (release), set the modDate to that date.

Fix modDate

---

biojava-structure/src/main/java/org/biojava/nbio/structure/domain/pdp/ClusterDomains.java

No other %f needed in the file

proper format of floating point (double) variable.

---

biojava-ontology/src/main/java/demo/ParseGO.java

filename of biosapiens.obo was incorrect, fixed

Ontology-demo filename typo

---

biojava-structure/src/main/java/org/biojava/nbio/structure/SubstructureIdentifier.java
biojava-structure/src/main/java/org/biojava/nbio/structure/URLIdentifier.java
biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmtf/MmtfStructureReader.java
biojava-structure/src/main/java/org/biojava/nbio/structure/scop/ScopDomain.java

This should fix #1019 and https://github.com/rcsb/symmetry/issues/113

Handling some nulls in PdbId creation

---

biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestURLBasedFileParsing.java

- per-assembly files moved to new location 
- https://www.rcsb.org/news/feature/62559153c8eabd0c4864f208

Update URL of Assembly CIF File in TestURLBasedFileParsing

---

biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenericInsdcHeaderFormat.java
biojava-core/src/test/java/org/biojava/nbio/core/sequence/io/GenbankWriterTest.java

Proposed fix and test for issue #886

#886 String Formatter error when key or value of Qualifier has character "%"

---

pom.xml

- bump ciftools-java version
- add my name to dev list

Keep ciftools up-to-date

---

CHANGELOG.md
biojava-structure/src/main/java/org/biojava/nbio/structure/io/LocalPDBDirectory.java
biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestURLBasedFileParsing.java

As per news announcement here: https://www.wwpdb.org/news/news?year=2022#6303be3b707ecd4f63b3d3d9
Also updated the changelog in preparation for next release

Switching to new DNS name for wwpdb http file server

---

biojava-structure/src/main/java/org/biojava/nbio/structure/io/cif/CifStructureConsumerImpl.java

Fixing issue with an edge case CIF parsing

---

biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenericGenbankHeaderFormat.java
biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenericInsdcHeaderFormat.java

Fixing genbank export new line issue

---

biojava-structure/src/main/java/org/biojava/nbio/structure/io/cif/CifStructureConsumerImpl.java

Following #1103 . This covers some fields that are missing in [PDB-IHM](https://pdb-ihm.org/) entries.

More on lenient PDBx/mmCIF parsing

---

biojava-structure/src/main/java/org/biojava/nbio/structure/io/cif/CifStructureConsumerImpl.java

Lenient cif parsing: allowing more missing fields. Also improved logging for the case of no atom_site

Parsing PDB-IHM CIF files

---

pom.xml

Should fix performance for some edge cases, see https://github.com/rcsb/ciftools-java/issues/13

Upgrade to latest ciftools-java version

---

biojava-structure/src/main/java/org/biojava/nbio/structure/Structure.java
biojava-structure/src/main/java/org/biojava/nbio/structure/StructureImpl.java

Plus some formatting/docs cleanup. The last commit (7217ee82acf8098206d67b67feb54c0ed5170b6a) is the important one for reviewing.

Adding safeguards when requesting chains from structure
