biojava3-structure/src/main/java/org/biojava/bio/structure/AtomPositionMap.java, biojava3-structure/src/main/java/org/biojava/bio/structure/ResidueRange.java, biojava3-structure/src/main/java/org/biojava/bio/structure/ResidueRangeAndLength.java, biojava3-structure/src/main/java/org/biojava/bio/structure/StructureTools.java, biojava3-structure/src/main/java/org/biojava/bio/structure/align/ce/CECPParameters.java, biojava3-structure/src/main/java/org/biojava/bio/structure/io/PDBFileParser.java, biojava3-structure/src/main/java/org/biojava/bio/structure/io/mmcif/chem/ResidueType.java, biojava3-structure/src/test/java/org/biojava/bio/structure/AtomPositionMapTest.java, biojava3-structure/src/test/java/org/biojava/bio/structure/ResidueRangeTest.java, biojava3-structure/src/test/java/org/biojava/bio/structure/align/util/AtomCacheTest.java, integrationtest/src/test/java/org/biojava/structure/test/StructureToolsTest.java, integrationtest/src/test/resources/1a4w.pdb
Provides many changes to `AtomPositionMap` and `ResidueRangeAndLength`.
* Replaces calcLength methods with getLength methods, which return the full length rather than length-1.
* Better inference for full-chain ranges
* Limited support for scop-style "_" wildcard chain names
* Better testing
=> Fix #244: AtomPositionMap bug fixes

biojava-structure/src/main/java/org/biojava/nbio/structure/xtal/CrystalCell.java, biojava-structure/src/test/java/org/biojava/nbio/structure/xtal/TestCrystalCell.java
Adds a translational component to an operator such that a particular point falls within the unit cell.
=> Add CrystalCell method to convert operators to function on the unit cell

biojava-structure/src/main/java/org/biojava/nbio/structure/Compound.java, biojava-structure/src/main/java/org/biojava/nbio/structure/StructureTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/contact/GroupContactSet.java, biojava-structure/src/main/java/org/biojava/nbio/structure/contact/ResidueIdentifier.java, biojava-structure/src/main/java/org/biojava/nbio/structure/contact/StructureInterface.java, biojava-structure/src/test/java/org/biojava/nbio/structure/TestCompoundResIndexMapping.java, biojava-structure/src/test/java/org/biojava/nbio/structure/contact/TestContactCalc.java, biojava-structure/src/test/java/org/biojava/nbio/structure/xtal/TestInterfaceClustering.java
This introduces a new minor feature Compound.getAlignedResIndex(), used for mapping residue numbers to the corresponding seqres residue indices. This was already possible via looking up the indices of Chain.getSeqresGroups(), but like this it is more convenient and a lot faster because the mapping is cached (lazily initialised).
This fixes contact overlap calculation for cases like 3ddo where all 6 chains have different residue numbers for the same entity.
=> New feature: Compound.getAlignedResIndex

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/StructureToolsTest.java, biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/ecod/EcodInstallationTest.java, biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/ecod/EcodParseTest.java, biojava-structure/src/main/java/org/biojava/nbio/structure/AtomPositionMap.java, biojava-structure/src/main/java/org/biojava/nbio/structure/ResidueNumber.java, biojava-structure/src/main/java/org/biojava/nbio/structure/ResidueRange.java, biojava-structure/src/main/java/org/biojava/nbio/structure/ResidueRangeAndLength.java, biojava-structure/src/main/java/org/biojava/nbio/structure/StructureTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/ecod/EcodFactory.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/chem/PolymerType.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/chem/ResidueType.java, biojava-structure/src/test/java/org/biojava/nbio/structure/AtomPositionMapTest.java, biojava-structure/src/test/java/org/biojava/nbio/structure/ResidueRangeTest.java
- Use phosphate atom as DNA representative atom
- Update PolymerType to for recent mmCIF values
- Handle imprecise residue ranges gracefully (finds overlap with valid residues, assuming
sequential numbering)
- Allow single-residue ranges (used by ECOD)
=> Misc updates for structure package

biojava-structure/src/main/java/org/biojava/nbio/structure/ResidueRangeAndLength.java, biojava-structure/src/main/java/org/biojava/nbio/structure/Structure.java, biojava-structure/src/main/java/org/biojava/nbio/structure/StructureImpl.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/FileConvert.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/MMCIFFileTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/SimpleMMcifConsumer.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/SimpleMMcifParser.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestDifficultMmCIFFiles.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestMMCIFWriting.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestNonDepositedFiles.java, biojava-structure/src/test/resources/org/biojava/nbio/structure/io/difficult_mmcif_quoting.cif
This should solve issues #188 and #234 
- basic mmcif writing: coordinates and crystallographic info
- any data in one of the beans in package `org.biojava.nbio.structure.io.mmcif.model` can be written to mmcif format using `org.biojava.nbio.structure.io.MMCIFFileTools.toMMCIF()`, which uses java reflection
- many fixes to the parser so that it can parse a broader set of files (including phenix-produced ones and biojava-produced ones!)
- all biojava-structure tests pass. The long parsing test in biojava-integrationtest also passes
=> Improving mmCIF support

biojava-genome/src/test/java/org/biojava/nbio/genome/GeneFeatureHelperTest.java
It was due to the test resource included that was built on linux and was not binary comparable to the one obtained at runtime in windows.
Discussed on mailing list in thread "Biojava genome test fails" with Jose Manuel Duarte.
=> Patched to allow tests to be completed on windows. 

biojava-structure/src/main/java/org/biojava/nbio/structure/io/FileParsingParameters.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/PDBFileParser.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/PDBFileReader.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/ChemCompGroupFactory.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/analysis/ScanSymmetry.java, biojava-structure/src/test/java/org/biojava/nbio/structure/ChemCompTest.java, biojava-structure/src/test/java/org/biojava/nbio/structure/PdbFileFormat30Test.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestChemCompProvider.java
See issue #313.
This pull request solves issue 313 by forcing the user to specify which *ChemCompProvider* is used when parsing a PDB or MMCiff file. The cache is kept and increased while the JVM is running, so *ChemComp* downloaded and cached by the *DownloadChemCompProvider* can also be user later by the *ReducedChemCompProvider*. The cache is never reset in the same JVM.
=> Fix313 - ChemCompProvider and ChemComp cache consistency

biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/CeSymm.java
Add a method to output alignments in I-TASSER's 3D Format, used for specifying an alignment for homology modelling.
The format is similar to PDB's ATOM records. See
http://zhanglab.ccmb.med.umich.edu/I-TASSER/option4.html
=> Output MultipleAlignment objects as an I-TASSER restraint file

biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/PermutationGroup.java
Replaced the previous nested loop algorithm with a breadth-first search.
This makes large-order groups (e.g. 40k permutations) finish in ms
rather than hours.
=> Fix #321. Optimized completeGroup() for large groups.

biojava-sequencing/src/main/java/org/biojava/nbio/sequencing/io/fastq/AbstractFastqWriter.java, biojava-sequencing/src/main/java/org/biojava/nbio/sequencing/io/fastq/Fastq.java, biojava-sequencing/src/main/java/org/biojava/nbio/sequencing/io/fastq/FastqTools.java, biojava-sequencing/src/main/java/org/biojava/nbio/sequencing/io/fastq/FastqVariant.java, biojava-sequencing/src/main/java/org/biojava/nbio/sequencing/io/fastq/IlluminaFastqWriter.java, biojava-sequencing/src/main/java/org/biojava/nbio/sequencing/io/fastq/SangerFastqWriter.java, biojava-sequencing/src/main/java/org/biojava/nbio/sequencing/io/fastq/SolexaFastqWriter.java, biojava-sequencing/src/test/java/org/biojava/nbio/sequencing/io/fastq/ConvertTest.java, biojava-sequencing/src/test/java/org/biojava/nbio/sequencing/io/fastq/FastqToolsTest.java, biojava-sequencing/src/test/java/org/biojava/nbio/sequencing/io/fastq/IlluminaFastqWriterTest.java, biojava-sequencing/src/test/java/org/biojava/nbio/sequencing/io/fastq/SangerFastqWriterTest.java, biojava-sequencing/src/test/java/org/biojava/nbio/sequencing/io/fastq/SolexaFastqWriterTest.java
Adds support for explicit conversions, e.g.
```java
// illumina --> sanger variant conversion
FastqReader reader = new IlluminaFastqReader();
FastqWriter writer = new SangerFastqWriter();
FileWriter fileWriter = new FileWriter(new File("sanger.fastq"));
for (Fastq fastq : reader.read(new File("illumina.fastq")))) {
writer.append(fileWriter, fastq.convertTo(FastqVariant.FASTQ_SANGER));
}
```
I'm not sure if the next release version will be 4.1.1 or 4.2 or 4.2.0, the ```@since``` tags will need to be updated accordingly.
=> adding Fastq.convertTo(FastqVariant) and supporting methods

pom.xml
Log4J should be fixed at 2.3, as per #364.
=> Downgrading Log4J to 2.3 for compatibility with Java 1.6

biojava-core/src/main/java/org/biojava/nbio/core/sequence/ProteinSequence.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/features/AbstractFeature.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/features/FeatureDbReferenceInfo.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/features/FeatureInterface.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenericInsdcHeaderFormat.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/template/AbstractSequence.java, biojava-core/src/test/java/org/biojava/nbio/core/sequence/io/GenbankReaderTest.java, biojava-core/src/test/java/org/biojava/nbio/core/sequence/loader/GenbankProxySequenceReaderTest.java
This is a pull request for reference #301 
The basic idea is to allow multiple key/values when parsing genbank files. That is the core change. The rest of the changes are to update getting/setting the fields and to modify the various places this code is called to handle the new format. Also add a test. This passes `mvn test`
on my machine. Happy to modify in response to feedback.
zach cp
=> Change AbstractFeature Qualifiers to a key:Array from key:value

biojava-structure/src/main/java/org/biojava/nbio/structure/io/FileParsingParameters.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/PDBFileParser.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/SeqRes2AtomAligner.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/SimpleMMcifConsumer.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/analysis/ScanSymmetry.java, biojava-structure/src/test/java/org/biojava/nbio/structure/Test2JA5.java, biojava-structure/src/test/java/org/biojava/nbio/structure/TestBond.java, biojava-structure/src/test/java/org/biojava/nbio/structure/TestStructureCrossReferences.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestHeaderOnly.java
These changes are to close out issue #353 (originally mmCIF parsing of SEQRES..).  Based on the design Steve Darnell suggested, these changes do the following:
Simplify the options:
* FileParsingParameters.storeEmptySeqRes option is dropped.
* FileParsingParameters.alignSeqRes is true by default.  When false, parsing will store seqres without aligning to AtomGroups.
* FileParsingParameters.headerOnly == true indicates that parsing should only take in header information and skip sections like Atoms, Sites, and Conects.  
Parsers:  
PDBFileParser and SimpleMMcifConsumer were updated for matching behaviors to the options.
When in headerOnly mode, parsing non-header sections return immediately to speed the parsing.
Tests:
Existing unit tests were updated for this change in the …
=> Improved headerOnly() performance and removing FileParsingParameters.storeEmptySeqRes.

biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/ChemCompGroupFactory.java
This is a small fix from issue #313.  If there was a search for a non-existent chemcomp group, this call causes a NPE that is prevented with a test.
=> Fix NPE in ChemCompGroupFactory

biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/DownloadChemCompProvider.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/ZipAppendUtil.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/ZipChemCompProvider.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/mmcif/TestChemCompProvider.java
Adding ZipChemCompProvider: pulls ChemComp files from a zip archive or download.
Adding ZipAppendUtil: manages updating the zip archive with new additions.
DownloadChemCompProvider: updated to add a check if the requested ChemComp
was found or threw FileNotFoundException.  downloadChemCompRecord() returns
true if it was successful.  getChemComp now checks if the download was
successful so that it won't throw an IOException if no chemcomp exists.
TestChemCompProvider unit test checks creation/addition with ZipChemCompProvider and includes 'bad' residues that would cause DownloadChemCompProvider to fail.
=> Adding ZipChemCompProvider. 

biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/ZipChemCompProvider.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/mmcif/TestChemCompProvider.java
Remove the singleton access for ZipChemCompProvider and make helper purgeAllTempFiles static.
These changes had missed the prior PR.
=> Zipchemcomp - pt2

biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/ChemCompGroupFactory.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/DownloadChemCompProvider.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/ReducedChemCompProvider.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/model/ChemComp.java, biojava-structure/src/test/java/org/biojava/nbio/structure/ChemCompTest.java
Adds additional check that files and streams are being closed in the ChemComp providers.
Also changes the ChemCompGroupFactory's behavior so that it does cache "empty"/stub chemicals
(since they will still be empty for the next fetch), but clears the cache when the provider changes.
This ensures that stub chemicals from a Reduced provider don't poison future fetches with the full
Download provider.
This should fix #395. Waters were being treated as "empty" due to an unfortunate choice of
one-letter code, and therefor not cached, leading to thousands of open handles to HOH.cif.gz.
=> Fix resource leaks with ChemComp

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/PDBFileParserTest.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/FileConvert.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/SimpleMMcifParser.java
This is pull request is to add "TER" records after chains when writing a PDB.  The PDB standard (http://deposit.rcsb.org/adit/docs/pdb_atom_format.html) describes that "The list of ATOM records in each polymer chain must be terminated by a TER record".  
* FileConvert writes "TER" line after each chain written out to the PDB file.
* Updated the PDBFileParserTest(s) to look also for the "TER" line when checking the PDB file output.
Also includes a check to prevent NPE in SimpleMMcifParser when trying to read a header for a zero-length file.
=> Implement missing TER records in the Structure.toPDB()

biojava-core/src/main/java/org/biojava/nbio/core/util/SingleLinkageClusterer.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/util/AtomCache.java, biojava-structure/src/main/java/org/biojava/nbio/structure/quaternary/io/BioUnitDataProviderFactory.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestQuaternaryStructureProviders.java
The old string-based API still works, but can now throw exceptions rather
than just logging the error and returning null. Better is to just pass the class
you want used directly.
Note that this also fixes a bug where setBioUnitDataProvider(String) checked the
validity of the previous provider, rather than the argument.
=> Refactoring BioUnitDataProviderFactory to take class arguments

.travis.yml, pom.xml
Upgrading to Java 8 for next developing cycle towards the 5.0 release, [as discussed in the mailing list](http://mailman.open-bio.org/pipermail/biojava-l/2016-January/011445.html)
=> Upgrading minimum requirement to java 8

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/StructureTest.java, biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/io/TestLongPdbVsMmCifParsing.java, biojava-structure/src/main/java/demo/DemoLoadStructure.java, biojava-structure/src/main/java/demo/DemoMMCIFReader.java, biojava-structure/src/main/java/org/biojava/nbio/structure/Chain.java, biojava-structure/src/main/java/org/biojava/nbio/structure/ChainImpl.java, biojava-structure/src/main/java/org/biojava/nbio/structure/EntityInfo.java, biojava-structure/src/main/java/org/biojava/nbio/structure/EntityType.java, biojava-structure/src/main/java/org/biojava/nbio/structure/Structure.java, biojava-structure/src/main/java/org/biojava/nbio/structure/StructureImpl.java, biojava-structure/src/main/java/org/biojava/nbio/structure/StructureTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/SubstructureIdentifier.java, biojava-structure/src/main/java/org/biojava/nbio/structure/contact/ResidueIdentifier.java, biojava-structure/src/main/java/org/biojava/nbio/structure/contact/StructureInterface.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/CAConverter.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/CompoundFinder.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/PDBFileParser.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/PDBFileReader.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/StructureSequenceMatcher.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/MMCIFFileTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/SimpleMMcifConsumer.java, biojava-structure/src/test/java/org/biojava/nbio/structure/PdbFileFormat30Test.java, biojava-structure/src/test/java/org/biojava/nbio/structure/SourceCompoundTest.java, biojava-structure/src/test/java/org/biojava/nbio/structure/TestCompoundHeuristics.java, biojava-structure/src/test/java/org/biojava/nbio/structure/TestCompoundResIndexMapping.java, biojava-structure/src/test/java/org/biojava/nbio/structure/TestStructureCrossReferences.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestMMcifOrganismParsing.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestNonDepositedFiles.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/mmcif/TestEntityNameAndType.java, biojava-structure/src/test/java/org/biojava/nbio/structure/xtal/TestInterfaceClustering.java
1) Refactored Compound to EntitiyInfo -> it seemed a better descriptiton.
2) Altered behaviour to consider non-polymer entities. 
This was required by MMTF and is I believe desired.
3) Added extra information (description and type).
These were required by MMTF and also generally useful.
=> Refactored compound to entity and altered behaviour to consider non-polymer compounds.

biojava-alignment/src/main/java/org/biojava/nbio/alignment/io/StockholmStructure.java, biojava-structure-gui/src/main/java/org/biojava/nbio/structure/align/gui/autosuggest/JAutoSuggest.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/FileConvert.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/PDBFileParser.java, biojava-structure/src/main/java/org/biojava/nbio/structure/jama/CholeskyDecomposition.java, biojava-structure/src/main/java/org/biojava/nbio/structure/jama/EigenvalueDecomposition.java, biojava-structure/src/main/java/org/biojava/nbio/structure/jama/LUDecomposition.java, biojava-structure/src/main/java/org/biojava/nbio/structure/jama/SingularValueDecomposition.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2178 - Short-circuit logic should be used in boolean contexts
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2178
M-Ezzat
=> squid:S2178 - Short-circuit logic should be used in boolean contexts

biojava-structure/src/main/java/org/biojava/nbio/structure/align/util/AtomCache.java
Specifically, set default alignSeqRes parameter in AtomCache  to true.
=> Fix #455. Use parsing params for AtomCache

biojava-structure/src/main/java/org/biojava/nbio/structure/StructureTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmtf/MmtfStructureReader.java
Fixed a bug in Structure Tools for empty arrays
Mmtf structure reader sets entity information both ways
=> Two small patches on StructureTools and MmtfStructureReader

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/ecod/EcodInstallationTest.java, biojava-structure/src/main/java/org/biojava/nbio/structure/ecod/EcodInstallation.java
Since ECOD releases every two weeks, we shouldn't cache version "latest" longer than that.
With this the cache is at most one version behind.
=> Automatically re-download ECOD if the cache is >2weeks old

biojava-structure/src/main/java/org/biojava/nbio/structure/contact/StructureInterface.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/FileConvert.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/MMCIFFileTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/model/CIFLabel.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/model/IgnoreField.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/model/Symmetry.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestMMCIFWriting.java
This provides a general solution to the problem in #480, which is that some CIF labels contain characters not permitted in java identifiers (like hyphens). Thus, a mechanism is needed for mapping java fields to the correct identifier for cases like `_symmetry.space_group_name_H-M` when writing to mmCIF.
This is implemented by adding two annotations. `@CIFLabel(label="str")` causes the cif property to be `_category.str`. `@IgnoreField` causes the field to be ignored entirely.
This pull also changes the MMCIFFileTools.toMMCIF method to be generic,
so that we enforce at compile time that all loop rows must be of the same type. The old method is deprecated (and should be backwards compatible if I understand type erasure correctly).
=> Fix #480: Allow CIF labels to differ from the java field name

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/StructureTest.java, biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/StructureToolsTest.java, biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/Test1a4w.java, biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/io/TestSeqResParsing.java, biojava-structure/src/main/java/demo/DemoContacts.java, biojava-structure/src/main/java/demo/DemoLoadStructure.java, biojava-structure/src/main/java/org/biojava/nbio/structure/Structure.java, biojava-structure/src/main/java/org/biojava/nbio/structure/StructureImpl.java, biojava-structure/src/main/java/org/biojava/nbio/structure/StructureTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/SubstructureIdentifier.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/FileConvert.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/utils/SymmetryTools.java, biojava-structure/src/test/java/org/biojava/nbio/structure/Test4hhb.java, biojava-structure/src/test/java/org/biojava/nbio/structure/TestAltLocs.java, biojava-structure/src/test/java/org/biojava/nbio/structure/align/util/AtomCacheTest.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/StructureSequenceMatcherTest.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestDifficultMmCIFFiles.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/mmcif/TestChemCompProvider.java
Refactored getChain(int chainIndex) and getChain(int modelNr, int chainIndex) to getChainByIndex().
This avoids ambiguity around whether the input can by a char (implicitally converted to an int).
=> Refactored getChain to getChainByIndex

biojava-aa-prop/src/main/java/org/biojava/nbio/aaproperties/PeptideProperties.java, biojava-aa-prop/src/main/java/org/biojava/nbio/aaproperties/PeptidePropertiesImpl.java, biojava-aa-prop/src/main/java/org/biojava/nbio/aaproperties/profeat/convertor/Convertor.java, biojava-core/src/main/java/org/biojava/nbio/core/alignment/SimpleProfile.java, biojava-core/src/main/java/org/biojava/nbio/core/alignment/matrices/AAIndexFileParser.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/CDSSequence.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/GeneSequence.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/FastaGeneWriter.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/util/IOUtils.java, biojava-genome/src/main/java/org/biojava/nbio/genome/parsers/gff/Feature.java, biojava-modfinder/src/main/java/org/biojava/nbio/protmod/io/ModifiedCompoundXMLConverter.java, biojava-structure-gui/src/main/java/org/biojava/nbio/structure/align/gui/GUIAlignmentProgressListener.java, biojava-structure-gui/src/main/java/org/biojava/nbio/structure/align/gui/aligpanel/AligPanel.java, biojava-structure-gui/src/main/java/org/biojava/nbio/structure/align/gui/aligpanel/MultipleAligPanel.java, biojava-structure-gui/src/main/java/org/biojava/nbio/structure/gui/util/SequenceScalePanel.java, biojava-structure/src/main/java/org/biojava/nbio/structure/StructureTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/BioJavaStructureAlignment.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/model/AfpChainWriter.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/multiple/mc/MultipleMcOptimizer.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/multiple/util/MultipleAlignmentTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/multiple/util/MultipleAlignmentWriter.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/xml/AFPChainXMLConverter.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/xml/HasResultXMLConverter.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/xml/PositionInQueueXMLConverter.java, biojava-structure/src/main/java/org/biojava/nbio/structure/contact/ResidueIdentifier.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmtf/MmtfStructureReader.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/utils/SymmetryTools.java, biojava-survival/src/main/java/org/biojava/nbio/survival/cox/SurvivalInfo.java, biojava-survival/src/main/java/org/biojava/nbio/survival/data/WorkSheet.java, biojava-survival/src/main/java/org/biojava/nbio/survival/kaplanmeier/figure/NumbersAtRiskPanel.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2131 - Primitives should not be boxed just for "String" conversion
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2131
M-Ezzat
=> squid:S2131 - Primitives should not be boxed just for String conversion

biojava-core/src/main/java/org/biojava/nbio/core/sequence/location/InsdcParser.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/xml/AFPChainXMLParser.java, biojava-structure/src/main/java/org/biojava/nbio/structure/jama/Matrix.java, biojava-structure/src/main/java/org/biojava/nbio/structure/secstruc/DSSPParser.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2130 - Parsing should be used to convert Strings to primitives
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2130
M-Ezzat
=> squid:S2130 - Parsing should be used to convert Strings to primitives

biojava-alignment/src/main/java/org/biojava/nbio/alignment/routines/AlignerHelper.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/CDSComparator.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/ExonComparator.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/SequenceComparator.java, biojava-genome/src/main/java/org/biojava/nbio/genome/parsers/gff/FeatureList.java, biojava-structure-gui/src/main/java/org/biojava/nbio/structure/align/gui/MyTableRowSorter.java, biojava-structure/src/main/java/org/biojava/nbio/structure/AtomPositionMap.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/helper/IdxComparator.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/pairwise/AltAligComparator.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/pairwise/FragmentJoiner.java, biojava-structure/src/main/java/org/biojava/nbio/structure/domain/pdp/SegmentComparator.java, biojava-survival/src/main/java/org/biojava/nbio/survival/cox/comparators/CoxVariablesOverallModelFitComparator.java, biojava-survival/src/main/java/org/biojava/nbio/survival/cox/comparators/MeanModelComparator.java, biojava-survival/src/main/java/org/biojava/nbio/survival/cox/comparators/SurvivalInfoComparator.java, biojava-survival/src/main/java/org/biojava/nbio/survival/cox/comparators/SurvivalInfoValueComparator.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2063 - Comparators should be "Serializable"
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2039
M-Ezzat
=> squid:S2063 - Comparators should be Serializable

biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmtf/MmtfStructureReader.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmtf/MmtfStructureWriter.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmtf/MmtfUtils.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/mmtf/TestBasicMmtf.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/mmtf/TestMmtfRoundTrip.java
1. Fix for the MmtfStructureReader to handle altLoc being a null byte.
2. Ensure groupType is upper case
3. SeqResGroups get a working chemComp
4. Added test that Biojava can roundtrip structures
=> MMTF roundtripping in Biojava

readme.md
It was 404 not found. I took the link from the homepage.
=> Fixed the cookbook link in the readme

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/PDBFileParserTest.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/PDBFileParser.java
The element information is filled using the **Chemical Component Dictionary** information, as discussed in #537.
=> Fix #537 - handle missing and empty Element column in PDB files

biojava-sequencing/src/test/java/org/biojava/nbio/sequencing/io/fastq/FastqTest.java
Immutability unit test fails when run as `mvn cobertura:cobertura`, Cobertura instrumented classes fail assertions.
See #561
=> Immutability test fails with Cobertura instrumented classes

biojava-structure/src/main/java/org/biojava/nbio/structure/io/BondMaker.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmtf/MmtfStructureReader.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmtf/MmtfStructureWriter.java, biojava-structure/src/test/java/org/biojava/nbio/structure/TestBond.java, pom.xml
- Fixed issues with reading a few MMTF files (related to hetatm vs amino)
- Fixed a bug in generation of disulphide bonds - including a test case.
- Fixed a null pointer exception from getAtomFromRecord
- Fixed handling of entities with no chains
- Upgrade to v1.0.0
- Fixed the formatting and added some javadocs
=> Version 1.0.0 of MMTF changes

biojava-structure/src/main/java/org/biojava/nbio/structure/io/FileConvert.java
Inserts space when altLoc is null, so that the rest of fields are properly aligned.
Two similar commits created by a mistake.
=> FileConvert altLoc fix

biojava-structure/src/main/java/org/biojava/nbio/structure/Atom.java, biojava-structure/src/main/java/org/biojava/nbio/structure/AtomImpl.java, biojava-structure/src/main/java/org/biojava/nbio/structure/Calc.java, biojava-structure/src/main/java/org/biojava/nbio/structure/ChainImpl.java, biojava-structure/src/main/java/org/biojava/nbio/structure/HetatomImpl.java, biojava-structure/src/main/java/org/biojava/nbio/structure/StructureTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/asa/AsaCalculator.java, biojava-structure/src/main/java/org/biojava/nbio/structure/contact/BoundingBox.java, biojava-structure/src/main/java/org/biojava/nbio/structure/contact/Contact.java, biojava-structure/src/main/java/org/biojava/nbio/structure/contact/Grid.java, biojava-structure/src/main/java/org/biojava/nbio/structure/contact/GridCell.java, biojava-structure/src/main/java/org/biojava/nbio/structure/quaternary/BioAssemblyTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/secstruc/SecStrucCalc.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/QuatSymmetrySubunits.java, biojava-structure/src/main/java/org/biojava/nbio/structure/xtal/UnitCellBoundingBox.java, biojava-structure/src/test/java/org/biojava/nbio/structure/TestCalc.java
This solves #582 enabling a faster and less memory intensive translation between `Atom[]` and `Point3d[]`. I've also made `AsaCalculator` and `Grid` (contact calculation algorithm) more independent of `Atom[]` following the comments of @pwrose in #545, now it's possible to use both algorithms with either just `Point3d[]` or with `Atom[]`.
=> Solving issue 582

biojava-structure/src/main/java/org/biojava/nbio/structure/Chain.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestHardBioUnits.java
This fixes the `TestHardBioUnits` test after PR #573. Now test is more reliable and actually tests that the right biounit is built.
=> Fixing hard biounits test

biojava-core/src/main/java/org/biojava/nbio/core/sequence/AccessionID.java, biojava-core/src/test/java/org/biojava/nbio/core/sequence/loader/GenbankProxySequenceReaderTest.java
Cherry-pick #598 to the bugfix branch. Solves #596.
=> Fix #596. Remove test for GenBank identifier parsing

biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/SimpleMMcifConsumer.java
One entry in the archive has a "?" in the seq_align_beg field. This causes a number format exception. According to mmCIF this is legitimate. So Biojava should handle this gracefully.
=> Add some handling of "?" in seq align position. E.g. for 5dn6

CHANGELOG, biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/StructureToolsTest.java, biojava-structure-gui/src/main/java/org/biojava/nbio/structure/symmetry/gui/SymmetryDisplay.java, biojava-structure-gui/src/main/java/org/biojava/nbio/structure/symmetry/gui/SymmetryListener.java, biojava-structure/src/main/java/org/biojava/nbio/structure/AtomIterator.java, biojava-structure/src/main/java/org/biojava/nbio/structure/Calc.java, biojava-structure/src/main/java/org/biojava/nbio/structure/Group.java, biojava-structure/src/main/java/org/biojava/nbio/structure/GroupIterator.java, biojava-structure/src/main/java/org/biojava/nbio/structure/Structure.java, biojava-structure/src/main/java/org/biojava/nbio/structure/StructureImpl.java, biojava-structure/src/main/java/org/biojava/nbio/structure/StructureTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/SubstructureIdentifier.java, biojava-structure/src/main/java/org/biojava/nbio/structure/contact/BoundingBox.java, biojava-structure/src/main/java/org/biojava/nbio/structure/contact/Grid.java, biojava-structure/src/main/java/org/biojava/nbio/structure/contact/GridCell.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/utils/SymmetryTools.java, biojava-structure/src/test/java/org/biojava/nbio/structure/TestAtomCache.java, biojava-structure/src/test/java/org/biojava/nbio/structure/TestAtomIterator.java
Fixes #560.
Clearly define ligand handling:
- Full-chain selections ('1abc.A') use all groups with that chain name, including waters and ligands
- Residue selections (1ab.A:1-100) do not include waters, and they may include ligands from other chains if they appear within the cutoff distance (5A default)
This PR also bundles some structural changes:
- Use StructureTools.addGroupsToStructure where ever you want to create a new structure. It handles the chain creation as needed.
This code was originally written for the 4.2 branch, but then moved to the 5.0 branch when it became apparent that it would change structure loading too much. As a result, during code review please pay special attention to places where the new chain model is used (e.g. ligands get their own chain), or where the new …
=> Improve ligand handling of substructures

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/StructureToolsTest.java, biojava-structure/src/main/java/org/biojava/nbio/structure/Chain.java, biojava-structure/src/main/java/org/biojava/nbio/structure/ChainImpl.java, biojava-structure/src/main/java/org/biojava/nbio/structure/ResidueNumber.java, biojava-structure/src/main/java/org/biojava/nbio/structure/ResidueRange.java, biojava-structure/src/test/java/org/biojava/nbio/structure/ResidueRangeTest.java
Allow partial residue ranges (#557)
- Introduce '^' and '$' symbols to stand for the beginning and end of the
chain. E.g. "A:^-100"
- Accept partial ranges for cases where they could not be confused with
negative residue numbers. E.g. "A:-5" refers to a single residue, while
"A:-+5" gives all residues up to and including 5.
=> Allow partial residue ranges (#557)

biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/ChemCompConsumer.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/MMcifConsumer.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/MetalBondConsumer.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/SimpleMMcifConsumer.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/SimpleMMcifParser.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/model/AtomSites.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/mmcif/TestAtomSitesParsing.java
A small patch to be able to parse the atom_sites category in mmcif. The category contains the same data as SCALE matrix records in PDB format. This can be useful to check the scale matrix is consistent with the standard reference frame, see https://github.com/eppic-team/owl/issues/4
=> Implementing parsing of atom_sites category in mmcif parser/consumer

biojava-structure/src/main/java/org/biojava/nbio/structure/io/PDBFileParser.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestShortLines.java
Submitting this pull request for fixes related to (closed) issue 330.  This adds line-length checks for CONECT, and restores parsing of LINK records that was lost in 4.2.4->4.2.5.  I found several example structures such as PDB:1MFD and PDB:5IKT that contain polysaccharide ligands for which the LINK record was necessary to correctly build bonds in BioJava.  Note, this functionality was previous present but was dropped in 4.2.5 (and does work with mmCIF parsing through _struct_conn).  
I also added an exception handler as discussed in mail to better handle exceptions while parsing individual lines of the PDB.
* Handle short lines with CONECT, LINK
* Restore bond building with LINK records
* Add an exception handler around line handlers for more robust parsing when
file format is violated.
=> Issue 330: fixes for PDB Parser

biojava-structure/src/main/java/org/biojava/nbio/structure/secstruc/SecStrucCalc.java, biojava-structure/src/test/java/org/biojava/nbio/structure/secstruc/TestSecStrucCalc.java
Fixes bug where structures with insertion codes were likely to have incorrect secondary structure assignments.  There were differences for a structure PDB:1DEU due to the SecStructCalc not using insertion codes when doing residue mappings.
=> Fix to the SecStrucCalc calculator to support insertion codes.

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/StructureToolsTest.java, biojava-structure/src/main/java/org/biojava/nbio/structure/Calc.java, biojava-structure/src/main/java/org/biojava/nbio/structure/NucleotideImpl.java, biojava-structure/src/main/java/org/biojava/nbio/structure/asa/AsaCalculator.java
This solves #631, and also adds  an important check to `Calc.getCentroid()`. Together with some minor logging changes. 
I've also implemented the same fix for the 4.2.x branch, I'll merge it when this is merged.
=> Fix for issue 631

biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/PermutationGroup.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/RotationGroup.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/RotationSolver.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/geometry/IcosahedralSampler.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/geometry/SphereSampler.java
In special cases it was possible to have pairs of axes that
pass our quality thresholds but form invalid symmetry groups.
Now alignments that superimpose a subunit onto itself are forbidden,
which should restrict it to the chiral groups.
Also add numerous notes and documentation.
=> Fix Quaternary symmetry symmetry detection bug

biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/Subunit.java
A small improvement for error handling in quaternary symmetry detection. With this we catch early cases of empty arrays that produce many problems downstream.
=> Catching early if the representative atom array is empty

biojava-genome/src/main/java/org/biojava/nbio/genome/util/ChromosomeMappingTools.java, biojava-genome/src/test/java/org/biojava/nbio/genome/TestGenomeMapping.java
- Fix in the chromosome mapping tool to return -1 if the genomic position falls outside coding region on the forward strand
- Test is added to check if the boundaries are handled correctly
=> Bugfix: chromosome mapping tool

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/align/AlignmentToolsTest.java, biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/align/seq/TestSmithWaterman3Daligner.java, biojava-structure/src/main/java/org/biojava/nbio/structure/StructureTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/seq/SmithWaterman3DParameters.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/seq/SmithWaterman3Daligner.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/seq/SmithWatermanUserArgumentProcessor.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/util/AlignmentTools.java
Implement the feature requested in #552. The sequence alignment from SmithWaterman is reduced until one of the two, minimum length or maximum RMSD, is fulfilled, in order to produce higher quality superposition outcomes.
=> Fix #552 maximum RMSD parameter to SmithWaterman3Daligner superpositions

biojava-structure/src/main/java/org/biojava/nbio/structure/secstruc/BetaBridge.java, biojava-structure/src/main/java/org/biojava/nbio/structure/secstruc/HBond.java, biojava-structure/src/main/java/org/biojava/nbio/structure/secstruc/Ladder.java, biojava-structure/src/main/java/org/biojava/nbio/structure/secstruc/SecStrucElement.java, biojava-structure/src/main/java/org/biojava/nbio/structure/secstruc/SecStrucInfo.java, biojava-structure/src/main/java/org/biojava/nbio/structure/secstruc/SecStrucState.java, biojava-structure/src/test/java/org/biojava/nbio/structure/TestStructureSerialization.java
This PR implements Serializable in the SecStruc objects that are stored in a Structure and adds the secondary structure to the serialized structure in the test.
The problem was reported by @lukeczapla in #673 and was missing from #676
=> Make secondary structure objects serializable

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/symmetry/TestQuatSymmetryDetectorExamples.java, biojava-structure-gui/src/main/java/demo/DemoQuatSymmetryJmol.java, biojava-structure/src/main/java/demo/DemoSymmetry.java, biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/SubunitCluster.java, biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/SubunitClusterUtils.java, biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/SubunitClusterer.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/QuatSymmetryDetector.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/QuatSymmetryResults.java
As discussed in #708, this removes isPseudoSymmetric and keeps only isPseudoStoichiometric. Also slightly changes the implementation of isPseudoStoichiometric.
=> Fixes for quaternary symmetry code

biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/SubunitExtractor.java
There are structures like 5M32 or 4LKE with synthetic constructs that do not have CA atoms, e.g. 4LKE chain G. Symmetry calculation fails for these structures.
=> ignore chains that do not have representative atoms

biojava-structure/src/main/java/org/biojava/nbio/structure/align/fatcat/calc/AFPOptimizer.java, biojava-structure/src/test/java/org/biojava/nbio/structure/align/TestAlignmentConsistency.java
If optimized alignment is shorter than the initial one, trailing zeros will remain.
As zero is a valid residue index, this may lead to broken logic when the alignment is processed further down the line, e.g., in subunit clustering for pseudo-symmetry. Sometimes it'll crash with large assemblies.
Not easy to write a reproducing example, as the alignment method is not customizable and is set to CE at the moment.  The smallest structure I found that would break a fatcat-based subunit clustering is 3J47 (without this fix).
=> Trimming zeroes in optimised alignment

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/cluster/TestSubunitClustererExamples.java, biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/symmetry/TestQuatSymmetryDetectorExamples.java, biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/SubunitClusterer.java, biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/SubunitClustererMethod.java, biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/SubunitClustererParameters.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/utils/SymmetryTools.java
Behaviour of SubunitClustererMethod.STRUCTURE can be confusing, as it always attempts clustering by sequence first, which may be undesirable. There is a 'hacky' way to ignore sequence clustering results, like is done here https://github.com/biojava/biojava/blob/f80f8bd3cc28cb5805f16f8b39d910eb0dba84b2/biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/utils/SymmetryTools.java#L758
but there is no way to not do it at all.
I suggest to split SubunitClustererMethod.STRUCTURE into two:
1) SubunitClustererMethod.STRUCTURE (cluster by structure only)
2) SubunitClustererMethod.SEQUENCE_STRUCTURE (new default, retains behaviour of current SubunitClustererMethod.STRUCTURE)
=> clustering methods reorganised

biojava-structure/src/main/java/org/biojava/nbio/structure/DBRef.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/PDBFileParser.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/SimpleMMcifConsumer.java
A small consistency fix related to #469 (data model refactoring).
Chain ID in the DBREF records is defined by pdbx_strand_id, which refers to author's version of the chain id, which is now called "chain name" in biojava.
=> chainId to chainName for dbref records

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/xtal/TestCrystalBuilder.java, biojava-structure/src/main/java/org/biojava/nbio/structure/StructureTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/contact/StructureInterfaceList.java, biojava-structure/src/main/java/org/biojava/nbio/structure/xtal/CrystalBuilder.java
Alternative solution to #728. 
Asymmetric unit extension is used with additional chains, as is currently done in biojava. The chain equivalence is tracked and passed on to the CrystalBuilder. As the result, it produces "clustered" list of interfaces based on NCS-equivalence (same original chains in the same relative position).
This change is not optimizing any calculations on its own (all redundant interfaces are still produced), but enables optimizations downstream by giving extra information. The client code must explicitly invoke this functionality and decide what to do with the chain/interface groups.
=> NCS-aware CrystalBuilder object

biojava-structure/src/main/java/org/biojava/nbio/structure/StructureTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/QuatSymmetryParameters.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/Stoichiometry.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/CeSymmIterative.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/GraphComponentOrderDetector.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/GraphComponentRefiner.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/utils/SymmetryTools.java
Another cleanup for the 5 release. UndirectedGraph was deprecated in jgrapht. 
Also removed a couple of warnings elsewhere.
=> Removing jgrapht library warnings, UndirectedGraph -> Graph

biojava-structure/src/main/java/org/biojava/nbio/structure/align/ce/AbstractUserArgumentProcessor.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/ce/GuiWrapper.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/util/AFPAlignmentDisplay.java
Fix for #594
The method `prepareGroupsForDisplay` had been moved to `AlignmentTools` in the `structure` module, but the references were not updated.
=> Fix the GuiWrapper class

biojava-structure/src/main/java/org/biojava/nbio/structure/io/PDBFileParser.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestNonDepositedFiles.java
Fixing PDB parsing issue. In some PDB files, valid CRYST1 records can be 58 columns only
=> Fix for CRYST1 parsing issue

biojava-integrationtest/pom.xml
More maven cleanup. There's no need to produce a jar file for integrationtest module. Maven was giving a warning for it.
=> Avoiding creation of an empty jar file for integrationtest module

pom.xml
See http://maven.apache.org/surefire/maven-surefire-plugin/usage.html
Currently surefire version 2.17 is silently pulled for an inexplicable reason, which causes it to ignore parameters in the pom file.
=> fix maven surefire plugin version

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/io/TestBioassemblies.java, biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/symmetry/TestQuatSymmetryDetectorExamples.java, biojava-structure/src/main/java/org/biojava/nbio/structure/StructureIO.java
Two small fixes for the integration tests.
Some tests override AtomCache, which may break others, in case they share the same JVM. In particular, MMTF and MMCIF might have different chain order. This is not important in general, but tests which assume deterministic results from the same input might fail.
=> AtomCache isolation

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/ecod/EcodInstallationTest.java, biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/ecod/EcodParseTest.java
This updates the ECOD tests to the latest version. The parser works fine, this just updates the test fixture to use more recent data. Since it doesn't have any public code, it can be included in either 5.0.0 or 5.0.1.
This probably should have been a part of #752 but I wanted to get the main changes out.
=> Update ECOD test

biojava-structure/src/main/java/org/biojava/nbio/structure/io/BondMaker.java
Check for missing insertion codes, for example, these are missing in mmcif files created by PDB-REDO.
=> Check for null when accessing insertion codes. This fixes #761.

pom.xml
`mvn site` wasn't working because `source` parameter was set to 1.7. 
This should allow publishing the javadocs, last step of #727 
I also upgraded to latest javadoc and site plugins
=> Fixing problems with mvn site

biojava-core/src/main/java/org/biojava/nbio/core/sequence/loader/UniprotProxySequenceReader.java
Uniprot now redirects to https. This fixes the URL, as well as adds code to do the redirect.
I couldn't find any existing code to follow redirects, but it would be useful to apply this to all downloads. The redirect code is a private static function in 4.2. In the 5.0 branch it would make sense to make it a utility method (e.g core/utils/FileDownloadUtils) and apply it everywhere we open HttpUrlConnections.
=> Fix NonstandardProteinCompoundTest failure

biojava-structure/src/main/java/org/biojava/nbio/structure/secstruc/SecStrucCalc.java
Related to the issue #789. 
I modified the SecStrucCalc class only for now, as it is currently affecting performance in my project. There may be other similar instances in the codebase, so the issue is not resolved yet.
=> SecStrucCalc - Logger string formatting changed to brackets.

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/io/TestBioassemblies.java, biojava-structure/src/main/java/org/biojava/nbio/structure/quaternary/BiologicalAssemblyBuilder.java
Fix for the issue #791, total order is now imposed.
=> Biological assembly builder, transformation ordering fix

.travis.yml, biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/embl/EmblId.java, biojava-protein-disorder/pom.xml, biojava-structure/pom.xml, pom.xml
Solves #804. Thanks @sbliven for most of the work.
This does:
- Keeps Java 8 compliance (compiled byte code is 8)
- Makes biojava work with java 9, 10 or 11 JREs
At some later point we can decide to move to next version of compliance (9, 10 or 11). That only requires changing the properties `jdk.version` and `maven.enforcer.jdk-version` in main pom.xml.
=> Make biojava work with java 9, 10, 11

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/io/TestBioassemblies.java, biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/SubunitExtractor.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/model/PdbxStructOperList.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmtf/MmtfStructureReader.java, biojava-structure/src/main/java/org/biojava/nbio/structure/quaternary/BiologicalAssemblyBuilder.java, biojava-structure/src/main/java/org/biojava/nbio/structure/quaternary/OperatorResolver.java
A solution to problem described in #801. 
* It assigns chain ids containing all operator ids, e.g. for chain id `A` where operators 5 and 61 have been applied, it assigns new chain id `A_5x61`
* A new test is added to check correct behaviour in cartesian product `_pdbx_struct_assembly_gen.oper_expression`  cases
* Some cleanup removing jama objects from `PdbxStructOperList` mmcif model bean
* For consistency, the `Subunit` objects used in symmetry detection now use asym_ids instead of author_ids.
=> Assembly chain ids for cases with composed operators in assembly expansion

biojava-structure/src/main/java/org/biojava/nbio/structure/StructureTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/utils/SymmetryTools.java
This provides shallow fixes for #816 and #817. By 'shallow' I mean that it fixes exceptions which were being thrown, but that there may be deeper issues. Neither bug is seems particularly serious, so I'd suggest merging this now and look for deeper issues later.
I have a test case for #817. It is kind of slow (runs CE-Symm) and needs structure-gui, so I've chosen to include it in the rcsb/symmetry project rather than in BioJava.
=> Fix CE-Symm errors

biojava-structure/src/main/java/org/biojava/nbio/structure/quaternary/BioAssemblyTools.java
Biological assembly builder requires this field, otherwise it does not work on reduced structures.
=> add EntityInfo to reduced structure

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/io/TestMMCIFWriting.java, biojava-structure/src/main/java/org/biojava/nbio/structure/EntityInfo.java, biojava-structure/src/main/java/org/biojava/nbio/structure/StructureImpl.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/MMCIFFileTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/quaternary/BiologicalAssemblyBuilder.java, biojava-structure/src/test/java/org/biojava/nbio/structure/TestCloning.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestMMCIFWriting.java
This prevented things like writing out to mmcif file a bioassembly with expanded chains.
=> Bugfix: expanded symmetry partner chains weren't added to entities

biojava-ontology/src/main/java/org/biojava/nbio/ontology/Synonym.java, biojava-ontology/src/test/java/org/biojava/nbio/ontology/TestOboFileParsing.java
Added a simple test to check a term with more than one synonym.
Solution is a modified implementation of Synonym.COMPARATOR.compare() that incorporates all fields of the class, case-insensitive.
=> Test and fix for BioJava #836 to parse and save all OBO synonyms

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/PDBFileParserTest.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/PDBFileParser.java
Making PDB parser not as strict and allowing for no padding at end of MTRIXn records
=> Fixing issue with MTRIXn record parsing and adding test for it

biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/SubunitCluster.java, biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/SubunitClusterer.java, biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/SubunitClustererParameters.java, biojava-structure/src/test/java/org/biojava/nbio/structure/cluster/TestSubunitCluster.java
This pull request introduces a new switch for the subunit clusterer used for symmetry detection. If the switch `useEntityIdForSeqIdentityDetermination` is enabled, it uses the entity id of the subunits to establish identity of sequences, saving the full Smith-Waterman alignment calculation.
This optimization is important in cases like large viral capsids, where there are many thousands of chains and all-to-all sequence alignments become a bottleneck. E.g. for 6Q1F the runtime goes from ~ 6 hours to 7 minutes.
=> Optimization of subunit clusterer for quaternary sym detection of PDB deposited structures

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/symmetry/TestQuatSymmetryDetectorExamples.java, biojava-structure/src/main/java/org/biojava/nbio/structure/EntityInfo.java, biojava-structure/src/main/java/org/biojava/nbio/structure/StructureTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/SubunitCluster.java, biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/SubunitClustererParameters.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/C2RotationSolver.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/QuatSymmetrySubunits.java, biojava-structure/src/test/java/org/biojava/nbio/structure/cluster/TestSubunitCluster.java
A follow up to #857 
This adds tests and fixes a few problems in the implementation (wasn't updating equivalent residues indices for chains of same entity). Also added docs and a new utility method in StructureTools.
In any case as of this PR I can't reproduce anymore the dramatic difference in runtime mentioned in #857 . One of the new (ignored) tests in this PR is to demonstrate the runtime difference, but it's only ~ 5x
=> Fixes on optimization of subunit clusterer for quaternary sym detection of PDB deposited structures

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/symmetry/TestQuatSymmetryDetectorExamples.java
Stoichiometry changed in January 2020 as indicated by @josemduarte in #867.
Since there are already many examples of local symmetry in the test I simply commented this one out, as it is no longer a case of local symmetry (it's a D5 assembly).
=> Comment out 3R8R from localSymmetry test

pom.xml
slf4j/log4j dependencies are quite old (>3 years), this PR updates
slf4j update 1.7.25 -> 1.7.30
log4j update 2.6.2 -> 2.13.1
=> Update slf4j/log4j dependencies

biojava-structure/src/main/java/org/biojava/nbio/structure/EntityType.java, biojava-structure/src/main/java/org/biojava/nbio/structure/Model.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmtf/MmtfStructureWriter.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestNonDepositedFiles.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/mmtf/TestMmtfRoundTrip.java
The [carbohydrate remediation project](https://www.mail-archive.com/ccp4bb@jiscmail.ac.uk/msg48559.html) introduces a new entity type: "branched". The type exists in the mmCIF dictionary for quite some time, but from July 2020 it will be used by many files with carbohydrates.
This pull request simply makes sure that the files can be parsed without breaking any existing functionality. It treats the branched chains as non-polymeric chains.
=> Minimal read support for files with 'branched' entities 

biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/ZipChemCompProvider.java
With some JDKs (openjdk-11) there is an (undocumented?)
`java.nio.file.FileSystems.newFileSystem(Path,Map<String,?>)`
method. This patch disambiguates which override to use for null.
Without it I was seeing the following compilation error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project biojava-structure: Compilation failure: Compilation failure:
[ERROR] /Users/bliven_s/ownCloud/dev/biojava_ws/biojava/biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/ZipChemCompProvider.java:[239,49] reference to newFileSystem is ambiguous
[ERROR]   both method newFileSystem(java.nio.file.Path,java.lang.ClassLoader) in java.nio.file.FileSystems and method …
```
=> Fix compilation bug in ZipChemCompProvider

biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/chem/ResidueType.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmtf/MmtfStructureReader.java
mmtf has it all upper-case - fails to lookup for chem.comp type because of different case
=> Case insensitive chem.comp type lookup

biojava-genome/src/main/java/org/biojava/nbio/genome/parsers/gff/GFF3Reader.java
The String-based functions are still here, and almost all the code is shared.
The Path overload allows everyone to read files via NIO providers, such as e.g.
the GCS NIO provider for reading files on Google Cloud Storage.
Key change: new BufferedReader(new FileReader(filename)) -> Files.newBufferedReader(path)
=> Add GFF3Reader overload that accepts Path

biojava-structure/src/main/java/org/biojava/nbio/structure/io/StructureSequenceMatcher.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmtf/MmtfStructureReader.java
As part of our course project CS527 at UIUC, we chose to fix flaky tests in Biojava project. Flaky tests are those tests that pass and fail without any code changes [https://hackernoon.com/flaky-tests-a-war-that-never-ends-9aa32fdef359]. Flaky tests are can be quite costly since they often require engineers to re-trigger entire builds on CI and often waste a lot of time waiting for new builds to complete successfully.
We used the NonDex tool to find flaky tests [ https://github.com/TestingResearchIllinois/NonDex ] . This is a tool developed in our research lab and has been widely accepted.
Iterating through the hashmap for entries is non-deterministic in nature, so we changed the HashMap to a LinkedHashMap and re-ran the test. The Junits were executed again and they passed. We ran the …
=> Fixing the flakiness caused by testGetProteinSequenceForStructure

CHANGELOG.md, biojava-structure/src/main/java/org/biojava/nbio/structure/PDBStatus.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/LocalPDBDirectory.java, biojava-structure/src/test/java/org/biojava/nbio/structure/PDBStatusTest.java
This replaces the legacy RCSB PDB API by the current one, so that `PDBStatus` continues working after legacy APIs are shutdown in December.
This is a breaking change with a changed `Status` enum and 2 fewer methods (getReplace, getReplaces). All documented in CHANGELOG
=> Rewrite of PDB status to use new RCSB PDB data API

biojava-structure/src/main/java/org/biojava/nbio/structure/PDBHeader.java
The test `org.biojava.nbio.structure.io.TestStructureSerialization#testSerializeStructure` is flaky due to the order in which Methods are appended into the StringBuilder `str.append(pdbHeader);` which is built in the toString method of the StructureImpl class.
The flakiness is observed due to the non-deterministic order of pdbHeader that can produce different structures.
The flaky test is fixed by sorting the array of Methods in PDBHeader.java class using a custom comparator in the toString method.
=> Flaky Test Fixed in TestStructureSerialization

biojava-structure/src/main/java/org/biojava/nbio/structure/PDBHeader.java
Reverts biojava/biojava#903
I may have been hasty on mergin #903, which changes mmcif output column order.
=> Revert "Flaky Test Fixed in TestStructureSerialization"

biojava-structure-gui/pom.xml, biojava-structure-gui/src/main/java/org/biojava/nbio/structure/symmetry/jmolScript/JmolSymmetryScriptGenerator.java, biojava-structure-gui/src/test/java/org/biojava/nbio/structure/symmetry/TestJmolSymmetryScriptGenerator.java, biojava-structure/src/main/java/org/biojava/nbio/structure/chem/ZipChemCompProvider.java, biojava-structure/src/test/java/org/biojava/nbio/structure/TestAtomCache.java
The core of this is the locale fix, which is necessary for CESymm/QuatSymm to function properly on non-US systems.
I've also included some commits for general cleanup and tests. If any of these are controversial I can revert them or move them to separate PRs.
=> Fix #917: Symmetry doesn't display with non-US locales

biojava-structure/src/main/java/org/biojava/nbio/structure/chem/ChemComp.java
ChemComps without parent would erroneously return an empty String. This restores the old behavior and will return `null`.
This fixes #921.
=> ChemComp#monNstdParentCompId now returns null instead of empty String

pom.xml
Changes to pom needed to perform a clean release to maven. I've tested it to produce a test 6.0.0-alpha1 and it worked fine. With this, releasing must now be done using the `release` profile, i.e. `mvn -Prelease release:prepare` and `mvn -Prelease release:perform`
Did some other pom cleanups too.
=> Improve mvn release process

biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenbankSequenceParser.java, biojava-core/src/test/java/org/biojava/nbio/core/sequence/io/GenbankReaderTest.java, biojava-core/src/test/resources/NC_018080.gb
Partly fixes #843 
- Corrected GenbankReader.java to parse anticodon qualifiers when they line wrap.
- Wrote new testGithub843 in GenbankReaderTest.java
- Added mentioned file NC_018080.gb downloaded from https://www.ncbi.nlm.nih.gov/nuccore/NC_018080
@josemduarte , can you please tell me where I can get NC_018080 in .embl file format? I couldn't find it.
=> Github issue 843 - Genebank parser

biojava-structure/src/main/java/org/biojava/nbio/structure/URLIdentifier.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/cif/CifStructureConverter.java
The file parsing parameters weren't respected by the new Cif reader.
=> Cif reader file parsing parameters fix

biojava-core/src/main/java/org/biojava/nbio/core/util/InputStreamProvider.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/mmtf/TestMmtfStructureReader.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/mmtf/TestMmtfStructureWriter.java
MS Windows has file and path problems:
1- spaces are not handled well in URL. Converting it to a URI handles decoding the path well.
2- TestURLIdentifier fails because when the connection is to a file and it contains parameters (e.g. ?format=PDB), they are perceived as part of the file name. getting the path first fixes it.
3- TestMmtfStructureReader and TestMmtfStructureWriter fail because Path does not handle drive specifier with a colon ':' (e.g. C:) well, while File does.
fixes #934
=> Fix #934 Several file and path issues on windows

biojava-structure/src/main/java/org/biojava/nbio/structure/chem/DownloadChemCompProvider.java
When the httpConnection is invalid, the application does not detect it, and it saves an empty (precisely a 20 bytes) file.
This fix detects when the connection is invalid or the file has no contents.
Related to #703
Adding a flag to be successful only when at least one byte is successfully read from the server
=> Fix #933 URLConnection to invalid HTTP URL is not detected as failure

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/TestSECalignment.java, biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/align/ce/OptimalCECPMainTest.java, biojava-structure/src/test/java/org/biojava/nbio/structure/ElementTest.java
Thought it might be useful to update the few remaining junit3 tests to use junit4; so that in the event the junit5 PR is accepted, there won't be 3 concurrent versions of junit tests, just 2.
=> update junit3->junit4 test, remove doc references to ju3

biojava-core/src/main/java/org/biojava/nbio/core/util/StringManipulationHelper.java, biojava-core/src/test/java/org/biojava/nbio/core/util/StringManipulationHelperTest.java
- identified and fixed a bug in equalsToIgnoreEndline if number of lines was different
- identified equalsToXml as not really mplemented or documented and not used
- re-implemented join() in simpler way using tests to validate unchanged behaviour and widened to accept a Collection rather than AbstractCollection
- some updated javadoc
- work towards #944
=> Tests for StringManipulationHelper

biojava-core/src/main/java/org/biojava/nbio/core/util/SingleLinkageClusterer.java, biojava-protein-disorder/src/main/java/org/biojava/nbio/ronn/ORonn.java, biojava-protein-disorder/src/main/java/org/biojava/nbio/ronn/ORonnModel.java, biojava-structure/src/main/java/org/biojava/nbio/structure/PDBCrystallographicInfo.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/fatcat/calc/AFPChainer.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/fatcat/calc/FCAlignHelper.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/model/AFPChain.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/model/AfpChainWriter.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/multiple/MultipleAlignmentImpl.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/multiple/util/MultipleAlignmentWriter.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/util/RotationAxis.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/xml/AFPChainXMLConverter.java, biojava-structure/src/main/java/org/biojava/nbio/structure/basepairs/BasePairParameters.java, biojava-structure/src/main/java/org/biojava/nbio/structure/contact/BoundingBox.java, biojava-structure/src/main/java/org/biojava/nbio/structure/domain/pdp/ClusterDomains.java, biojava-structure/src/main/java/org/biojava/nbio/structure/domain/pdp/Cut.java, biojava-structure/src/main/java/org/biojava/nbio/structure/domain/pdp/CutDomain.java, biojava-structure/src/main/java/org/biojava/nbio/structure/secstruc/SecStrucState.java, biojava-structure/src/main/java/org/biojava/nbio/structure/xtal/CrystalCell.java, biojava-structure/src/main/java/org/biojava/nbio/structure/xtal/CrystalTransform.java, biojava-structure/src/main/java/org/biojava/nbio/structure/xtal/SpaceGroup.java
#918 showed that locales which use commas for floating-point numbers
can cause problems with output formats. This commit fixes a number
of other cases.
- Force Locale.US when outputting floats to files/streams
- Usually don't force Locale.US when outputting floats to standard out &
logging (would lead to more consistent logs but breaks localization)
- Replace some `println(String.format(` calls with Java 5 `printf`
=> Force US Locale for floats.

biojava-core/src/main/java/org/biojava/nbio/core/util/Equals.java, biojava-core/src/main/java/org/biojava/nbio/core/util/FileDownloadUtils.java, biojava-core/src/main/java/org/biojava/nbio/core/util/FlatFileCache.java, biojava-core/src/main/java/org/biojava/nbio/core/util/SoftHashMap.java, biojava-core/src/test/java/org/biojava/nbio/core/HashcoderTest.java, biojava-core/src/test/java/org/biojava/nbio/core/util/EqualsTest.java, biojava-core/src/test/java/org/biojava/nbio/core/util/FileDownloadUtilsTest.java, biojava-core/src/test/java/org/biojava/nbio/core/util/FlatFileCacheTest.java, biojava-core/src/test/java/org/biojava/nbio/core/util/HashcoderTest.java, biojava-core/src/test/java/org/biojava/nbio/core/util/SingleLinkageClustererTest.java, biojava-core/src/test/java/org/biojava/nbio/core/util/SoftHashMapTest.java
Added test-classes for several util classes. Mostly routine, a few comments. Planned to add tests for all remaining util methods but that would be a monster PR so breaking into 2. 
- added Javadocs I thought would be useful after discovering behaviour through testing
- In a few cases added some obvious error handling  but made minimal changes to source code
- FileDownloadUtils is tricky to test some of the download methods, without doing some refactoring to mock/stub the actual network call and be able to configure timeout to not be hardcoded to 60s
- SingleLinkageClustererTest is quite basic. I followed the Wikipedia example entry and the results from the code are quite similar but not identical to the worked example. Not sure if this is important or relevant in the context in which it's …
=> Tests for core util package

CHANGELOG.md, biojava-core/src/main/java/org/biojava/nbio/core/util/CRC64Checksum.java, biojava-core/src/test/java/org/biojava/nbio/core/util/CRC64ChecksumTest.java
Test for basic behaviour of Crc64Checksum - #944
I think there is a bug exposed by test `partialbyteRange()` and I've proposed a solution in the Crc64Checksum class.
=> CRC64Checksum test #944

biojava-integrationtest/pom.xml, biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/io/TestBondParsing.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/BondMaker.java
This should fix #943 
@richarda23 I've created a new integration test with junit5. Can you double check that's ok? Question: is the junit-vintage-engine required?
=> Bond parsing in PDB format now uses chain ids correctly

biojava-structure/src/main/java/org/biojava/nbio/structure/scop/ScopFactory.java, biojava-structure/src/main/java/org/biojava/nbio/structure/scop/ScopInstallation.java, biojava-structure/src/test/java/org/biojava/nbio/structure/align/util/AtomCacheTest.java
All SCOP installation file downloads fail because all files before 2.08
no longer exist (error 404).
1- All downloads are corrected by upgrading the LATEST_VERSION to 2.08.
2- testGetStructureForChainlessDomains is ignored because chainless
domains are present only in SCOP < 1.73
=> Fix 969 Update SCOP version to 2.08

pom.xml
- ciftools 3.0.0 (brings AlphaFold/model support to the table)
- ~propose to ignore `openchart` dependency as it doesn't seem to be used - somebody should confirm this, I've never used any of the forester stuff~
- ~with that exclusion, a dependency on jackson-databind was needed~
- ~`Acetylation_site_dataset.gz` reports 403 in tests and on console, but can be downloaded manually via the browser, added this as 1 MB test resource to circumvent test issues~
=> Update ciftools dependency and fix build/tests

CHANGELOG.md, biojava-structure/src/main/java/org/biojava/nbio/structure/chem/DownloadChemCompProvider.java, biojava-structure/src/test/java/org/biojava/nbio/structure/chem/TestDownloadChemCompProvider.java
This makes it possible to point DownloadChemCompProvider to any custom CCD repository, with any layout. Related to recent additions to ftp.rcsb.org (see [news announcement](https://www.rcsb.org/news?year=2021&article=613b93b3ef055f03d1f222cf&feature=true) )
=> A flexible system for passing custom URL layout in DownloadChemCompProvider

biojava-aa-prop/pom.xml, biojava-core/pom.xml, biojava-modfinder/pom.xml, biojava-protein-disorder/pom.xml, biojava-structure/pom.xml, pom.xml
There was an issue with running CeSymm on java 15+ (rcsb/symmetry#104). I suspect that this issue effected all projects that include biojava with the maven-shade-plugin. I was able to trace the problem back to the old com.sun.xml.bind implementations. Switching these to the glassfish JAXB implementation fixed the problem.
- Downgrade jgrapht to maintain java 8 support
- Switch JAXB to glassfish implementation for better java 15+ support
=> Change JAXB implementation for better java version compatibility

biojava-structure/src/main/java/org/biojava/nbio/structure/PDBHeader.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/PDBFileParser.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/cif/CifStructureConsumer.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/cif/CifStructureConsumerImpl.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/cif/CifStructureConverter.java
Apparently it affects only cryo-EM entries.
Partially Fixes #1000 
It fixes the PDBFileParser.
Before fixing the mmCifParser we need first to check whether the files should be remediated or not.
=> Parsing resolution values in PDB (REMARK 2 and REMARK 3 [new format]) and mmCif

biojava-alignment/src/main/java/org/biojava/nbio/alignment/routines/AlignerHelper.java, biojava-alignment/src/test/java/org/biojava/nbio/alignment/TestDNAAlignment.java
Using a local alignment with linear gap penalty resulted in the failure trace below. Setting pointers to dimension (ye+1,1) fixed the error. Added a test "testLinearAlignmentLocal()" in TestDNAAlignment.java to verify results. 
java.lang.NullPointerException: Cannot store to object array because "pointers[y]" is null
at org.biojava.nbio.alignment.routines.AlignerHelper.setScoreVector(AlignerHelper.java:587)
at org.biojava.nbio.alignment.routines.AlignerHelper.setScoreVector(AlignerHelper.java:560)
at org.biojava.nbio.alignment.template.AbstractMatrixAligner.align(AbstractMatrixAligner.java:347)
at org.biojava.nbio.alignment.template.AbstractPairwiseSequenceAligner.getPair(AbstractPairwiseSequenceAligner.java:114)
at org.biojava.nbio.alignment.TestDNAAlignment.testLinearAlignmentLocal(TestD …
=> Fix local align score vector

.github/workflows/master.yml, .github/workflows/pull_request.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

biojava-core/src/main/java/org/biojava/nbio/core/sequence/features/DBReferenceInfo.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenbankReader.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenbankSequenceParser.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenbankWriter.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenbankWriterHelper.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenericGenbankHeaderFormat.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenericGenbankHeaderParser.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenericInsdcHeaderFormat.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/location/InsdcParser.java, biojava-core/src/test/java/org/biojava/nbio/core/sequence/io/GenbankWriterTest.java, biojava-core/src/test/resources/with_joins.gb
Hello, 
I have been working on the issue that a GenBank file read in through the parser and then written back out will result in loss of information from the original file. While looking into this I have also fixed a few other issues with the parser and writer for Genbank files. The highlights of this work includes:
- added a new writer helper method that will retain the information in the original locus line
- fixed writing out db_xref feature qualifiers which was not working
- fixed writing out the accession version and GI ID
- allow locus ids that contain spaces
- allow the locus id to be empty
- fixed writing out feature locations containing joins and partial locations
- fixed reading and writing locations on multiple lines
- Maintained quotes around feature qualifier values in files …
=> GenBankWriter does not use information in the original header #942

biojava-aa-prop/src/main/java/org/biojava/nbio/aaproperties/IPeptideProperties.java, biojava-aa-prop/src/main/java/org/biojava/nbio/aaproperties/PeptideProperties.java, biojava-aa-prop/src/main/java/org/biojava/nbio/aaproperties/PeptidePropertiesImpl.java, biojava-aa-prop/src/test/java/org/biojava/nbio/aaproperties/PeptidePropertiesImplTest.java
Calculates the aromaticity value of a protein according to Lobry, 1994.
It is simply the relative frequency of Phe(F)+Trp(W)+Tyr(Y).
=> Aromaticity calculation (Protein) #1037

pom.xml
Bump dependency 4.0.5 to Fix cif writing in non-US locales.
Thanks @JonStargaryen for fixing the bug at **ciftools-java**.
Fixes #1049.
=> Bump dependency ciftools-java-jdk8 to 4.0.5

biojava-core/src/main/java/org/biojava/nbio/core/util/FileDownloadUtils.java, biojava-core/src/test/java/org/biojava/nbio/core/util/FileDownloadUtilsTest.java, biojava-structure/src/main/java/org/biojava/nbio/structure/ecod/EcodFactory.java, biojava-structure/src/main/java/org/biojava/nbio/structure/ecod/EcodInstallation.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/LocalPDBDirectory.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/sifts/SiftsMappingProvider.java, biojava-structure/src/main/java/org/biojava/nbio/structure/scop/ScopInstallation.java
When a file is being downloaded, two metadata files are created for size and hash (as possible).
I applied this validation framework to the files I know (structure files, SCOP installations, Ecod installation).
In case anybody knows something else where downloaded files can be validated, please advise.
I did not implement the hash code _at least yet_, because I don't know a place where a hash file is distributed with the resource file. In case anybody knows some example, please advise.
@sbliven was proposing to download to a temporary file before moving the load to the destination file. I found that `FileDownloadUtils.downloadFile()` does. Therefore, no need to do it ourselves. again, in case anybody knows a place which downloads files but does not use `FileDownloadUtils.downloadFile()` …
=> Add file download validation

pom.xml
Needed for the 7.0.0 release as discussed in #1035 
After this, the minimum required JRE to run biojava (or projects that use it) is JRE 11
=> Upgrading source and target to java 11

pom.xml
- need Maven descriptors for `pom.properties` files when using BioJava as dependency
- this ensures that they are added to the artifacts
=> POM Cleanup: Add Maven descriptors & remove mention of Travis CI

biojava-structure/src/main/java/org/biojava/nbio/structure/StructureTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/contact/StructureInterface.java, biojava-structure/src/main/java/org/biojava/nbio/structure/xtal/CrystalTransform.java
The method getBackboneAtomArray had a cyclomatic complexity of 22, hence refactored the method was to optimize the code.
This refactoring can be qualified as extract method refactoring.
The logic and the output after refactoring remain the same.
=> Refactoring : Extract method getBackboneAtomArray changes to reduce the cyclomatic complexity

biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/io/cif/CifFileSupplierIntegrationTest.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/SeqRes2AtomAligner.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/cif/AbstractCifFileSupplier.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/cif/CifStructureConsumerImpl.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/TestNonDepositedFiles.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/cif/CifFileSupplierImplTest.java, pom.xml
Adding `_entity` and `_entity_poly` to CIF output, so that some more metadata is available for consumers.
Also: 
- now adding seqres groups to `Chain`s when no entity info is present in input file
- upgrading to latest ciftools-java
=> Some more categories written out to CIF 

biojava-aa-prop/src/main/java/org/biojava/nbio/aaproperties/xml/AminoAcidCompositionTable.java, biojava-alignment/src/main/java/org/biojava/nbio/alignment/io/StockholmFileParser.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenericGenbankHeaderParser.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/IUPACParser.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/util/IOUtils.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/loader/UniprotProxySequenceReader.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/location/InsdcParser.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/storage/BitSequenceReader.java, biojava-core/src/main/java/org/biojava/nbio/core/sequence/storage/JoiningSequenceReader.java, biojava-ontology/src/main/java/org/biojava/nbio/ontology/IntegerOntology.java, biojava-ontology/src/main/java/org/biojava/nbio/ontology/Ontology.java, biojava-ontology/src/main/java/org/biojava/nbio/ontology/utils/AbstractAnnotation.java, biojava-ontology/src/main/java/org/biojava/nbio/ontology/utils/Annotation.java, biojava-ontology/src/main/java/org/biojava/nbio/ontology/utils/EmptyAnnotation.java, biojava-protein-disorder/src/main/java/org/biojava/nbio/ronn/Jronn.java, biojava-protein-disorder/src/main/java/org/biojava/nbio/ronn/ModelLoader.java, biojava-protein-disorder/src/main/java/org/biojava/nbio/ronn/ORonn.java, biojava-structure-gui/src/main/java/demo/AFPFromFasta.java, biojava-structure/src/main/java/org/biojava/nbio/structure/AtomIterator.java, biojava-structure/src/main/java/org/biojava/nbio/structure/Element.java, biojava-structure/src/main/java/org/biojava/nbio/structure/GroupIterator.java, biojava-structure/src/main/java/org/biojava/nbio/structure/PdbId.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/pairwise/AlignmentResult.java, biojava-structure/src/main/java/org/biojava/nbio/structure/quaternary/BioAssemblyTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/quaternary/OperatorResolver.java, biojava-structure/src/main/java/org/biojava/nbio/structure/scop/ScopInstallation.java
This is a fix on https://github.com/biojava/biojava/issues/1061
The goal is to remove all unnecessary exception declarations or that overload the method declaration. All RuntimeExceptions are suppressed as they are automatically propagated by Java. When the method declaration contains a checked exception as well as a parent exception, only the parent exception is kept because the derived exception is also automatically picked up by the parent exception declaration.
Our automatic defect correction solution detected and corrected 72 violations of the Sonar S1130 rule '"throws" declarations should not be superfluous'. According to Sonar, it would have taken 6 hours to identify and correct these violations.
We hope that this PR suits you and allows you to improve the quality of your project.
=> Fix Sonar S1130 throws declarations should not be superfluous

biojava-protein-disorder/src/main/java/org/biojava/nbio/ronn/ORonn.java, biojava-protein-disorder/src/main/java/org/biojava/nbio/ronn/ORonnModel.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/util/SynchronizedOutFile.java
This fix is specific to constructor declarations.
=> Second fix for sonar rule 's1130' throws declarations should not be superfluous

biojava-structure/src/main/java/org/biojava/nbio/structure/scop/ScopInstallation.java
I was going through the tutorial and was displaying a jmol panel.  When I selected Show SCOP Domains for the color on the selection, I received a `FileNotFoundException`.   A review of the Berkeley site shows that they changed from http to https for the scheme.   They also appear to have changed the path portion of the URL in version 2 from 'scop' to 'scope.'
All of the unit tests worked before and after this change.  I tried to create a unit test to show the failure, fix it, and run the unit test to show that it was fixed, but I couldn't quite follow the path to get to the ScopInstallation code from the Swing application.
To recreate my original error, the following code can be used (derived from the tutorial).
```
Structure structure = StructureIO.getStructure("4FRW"); …
```
=> Changed the SCOP Installation URLs

biojava-structure/src/main/java/org/biojava/nbio/structure/io/cif/CifStructureConsumerImpl.java, biojava-structure/src/test/java/org/biojava/nbio/structure/io/cif/CifFileConsumerImplTest.java
[ESMAtlas](https://esmatlas.com/) files miss some of the atom_site fields, which was breaking their parsing. This makes parsing more lenient, not requiring these fields if not present.
=> More lenient mmCIF parsing

biojava-core/src/main/java/org/biojava/nbio/core/util/FileDownloadUtils.java, biojava-core/src/main/java/org/biojava/nbio/core/util/SingleLinkageClusterer.java, biojava-genome/src/main/java/org/biojava/nbio/genome/util/ChromosomeMappingTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/ChainImpl.java, biojava-structure/src/main/java/org/biojava/nbio/structure/StructureTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/StructurePairAligner.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/pairwise/FragmentJoiner.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/seq/SmithWaterman3Daligner.java, biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/SubunitExtractor.java, biojava-structure/src/main/java/org/biojava/nbio/structure/contact/StructureInterfaceList.java, biojava-structure/src/main/java/org/biojava/nbio/structure/domain/SerializableCache.java, biojava-structure/src/main/java/org/biojava/nbio/structure/geometry/SuperPositionQCP.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/EntityFinder.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/LocalPDBDirectory.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/PDBFileParser.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/SeqRes2AtomAligner.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/cif/CifStructureConsumerImpl.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/sifts/SiftsMappingProvider.java, biojava-structure/src/main/java/org/biojava/nbio/structure/io/sifts/SiftsXMLParser.java, biojava-structure/src/main/java/org/biojava/nbio/structure/scop/Astral.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/HelixSolver.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/CeSymm.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/CeSymmIterative.java, biojava-structure/src/main/java/org/biojava/nbio/structure/xtal/CrystalBuilder.java
Some method calls can effectively be "no-ops", meaning that the invoked method does nothing, based on the application’s configuration (eg: debug logs in production). However, even if the method effectively does nothing, its arguments may still need to evaluated before the method is called. This fix improves performance, especially in cases where concatenation is used at low logging levels.
=> Fix sonar issue 2629 Logging arguments should not require evaluation

biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenericFastaHeaderParser.java
Hi,
We find that there exist container inefficiency in GenericFastaHeaderParser.java.
In particular, at lines 96 and 97 in GenericFastaHeaderParser.java, the for loop keep allocating the `data` array and transform container object `values` to array, which incurs redundant memory allocation and container operations.
We discovered the above containers inefficiencies by our tool cinst. The patch is submitted. Could you please check and accept it? We have tested the patch on our PC. The patched program works well.
=> Fix container inefficiency in GenericFastaHeaderParser.java

biojava-aa-prop/pom.xml, biojava-alignment/pom.xml, biojava-core/pom.xml, biojava-genome/pom.xml, biojava-integrationtest/pom.xml, biojava-modfinder/pom.xml, biojava-ontology/pom.xml, biojava-protein-comparison-tool/pom.xml, biojava-protein-disorder/pom.xml, biojava-structure-gui/pom.xml, biojava-structure/pom.xml, biojava-survival/pom.xml, biojava-ws/pom.xml, pom.xml
=> Upgrading to slf4j2

biojava-structure-gui/src/main/java/org/biojava/nbio/structure/align/gui/MenuCreator.java, biojava-structure-gui/src/main/java/org/biojava/nbio/structure/align/gui/MultipleAlignmentJmolDisplay.java, biojava-structure-gui/src/main/java/org/biojava/nbio/structure/align/gui/MySaveFileListener.java, biojava-structure-gui/src/main/java/org/biojava/nbio/structure/align/gui/jmol/MultipleAlignmentJmol.java, biojava-structure-gui/src/main/java/org/biojava/nbio/structure/symmetry/jmolScript/JmolSymmetryScriptGeneratorPointGroup.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/multiple/Block.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/multiple/mc/MultipleMcOptimizer.java, biojava-structure/src/main/java/org/biojava/nbio/structure/align/multiple/util/MultipleAlignmentTools.java, biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/SubunitCluster.java, biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/SubunitClustererMethod.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/QuatSymmetrySubunits.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/internal/SymmOptimizer.java, biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/utils/SymmetryTools.java, biojava-structure/src/test/java/org/biojava/nbio/structure/symmetry/internal/TestCeSymm.java, biojava-structure/src/test/resources/AF-V9WDR2-F1-model_v4.cif
This fixes rcsb/symmetry#118.
It switches the determination of the symmetry group and rotation axes to use the CESymm alignment directly. Before it was recomputed using QuatSymmDetector, which failed with short repeats.
A new CE-Symm version will be released after the next biojava release.
=> Fix CE-Symm bug with short repeats

biojava-structure/src/main/java/org/biojava/nbio/structure/io/cif/CifStructureConsumerImpl.java
mmCIF files generated by packages like Gemmi don't have all the fields that archived PDB files do. This makes the parser more lenient to some missing fields. See https://github.com/rcsb/rcsb-api-tools/issues/8
=> More lenient CIF parsing

biojava-structure/src/main/java/org/biojava/nbio/structure/asa/AsaCalculator.java
With this the default `AsaCalculator` constructor will use model 1 only. Also introduced a new constructor to choose the model.
=> ASA calculation should be done per model

biojava-structure/src/main/java/org/biojava/nbio/structure/EntityType.java
Some PDB-IHM files use upper case, unlike PDB files that use lower case.
=> CIF parsing: entity type should be case insensitive
